CREATE TABLE IF NOT EXISTS `agent_token_usage` (
  `id` bigint NOT NULL,
  `thread_id` bigint NOT NULL,
  `run_id` bigint NOT NULL,
  `space_id` bigint NOT NULL,
  `source` varchar(32) NOT NULL,
  `step_id` varchar(128) NOT NULL DEFAULT '',
  `step_index` int NOT NULL DEFAULT 0,
  `step_name` varchar(128) NOT NULL DEFAULT '',
  `model_name` varchar(128) NOT NULL DEFAULT '',
  `provider` varchar(64) NOT NULL DEFAULT '',
  `input_tokens` bigint NOT NULL DEFAULT 0,
  `output_tokens` bigint NOT NULL DEFAULT 0,
  `total_tokens` bigint NOT NULL DEFAULT 0,
  `cost_micros` bigint NOT NULL DEFAULT 0,
  `currency` varchar(16) NOT NULL DEFAULT '',
  `estimated` tinyint(1) NOT NULL DEFAULT 0,
  `raw_usage` json DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `created_at` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agent_token_usage_thread_run` (`thread_id`, `run_id`),
  KEY `idx_agent_token_usage_space_source` (`space_id`, `source`),
  KEY `idx_agent_token_usage_run_source` (`run_id`, `source`),
  KEY `idx_agent_token_usage_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
