-- Persist AppDev provider execution ownership and recovery state.
CREATE TABLE `appdev_provider_executions` (
  `id` varchar(64) NOT NULL,
  `space_id` bigint unsigned NOT NULL,
  `project_id` varchar(64) NOT NULL,
  `generation` bigint unsigned NOT NULL,
  `idempotency_key` varbinary(128) NOT NULL,
  `desired_state` varchar(32) NOT NULL,
  `observed_state` varchar(32) NOT NULL,
  `provider_key` varchar(64) NOT NULL,
  `provider_scope` varchar(32) NOT NULL,
  `provider_execution_id` varbinary(128) NOT NULL,
  `submission_started_at` datetime(6) DEFAULT NULL,
  `checkpoint_envelope` mediumtext NOT NULL,
  `checkpoint_write_revision` bigint unsigned NOT NULL DEFAULT 0,
  `checkpoint_write_pending` tinyint(1) NOT NULL DEFAULT 0,
  `checkpoint_write_operation_hash` binary(32) DEFAULT NULL,
  `checkpoint_write_expires_at` datetime(6) DEFAULT NULL,
  `checkpoint_last_operation_hash` binary(32) DEFAULT NULL,
  `cleanup_operation_hash` binary(32) DEFAULT NULL,
  `terminal_operation_hash` binary(32) DEFAULT NULL,
  `release_owner_operation_hash` binary(32) DEFAULT NULL,
  `provider_lease_expires_at` datetime(6) DEFAULT NULL,
  `owner_identity_hash` binary(32) DEFAULT NULL,
  `owner_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `owner_expires_at` datetime(6) DEFAULT NULL,
  `preview_route` varchar(512) NOT NULL DEFAULT '',
  `artifact_object_key` varchar(512) NOT NULL DEFAULT '',
	`build_operation_id` varbinary(128) NOT NULL DEFAULT '',
	`build_operation_hash` binary(32) DEFAULT NULL,
	`artifact_status` varchar(32) NOT NULL DEFAULT 'none',
	`artifact_kind` varchar(64) NOT NULL DEFAULT '',
	`artifact_digest` varchar(71) NOT NULL DEFAULT '',
	`artifact_size` bigint unsigned NOT NULL DEFAULT 0,
	`artifact_version` bigint unsigned NOT NULL DEFAULT 0,
	`build_started_at` datetime(6) DEFAULT NULL,
	`artifact_updated_at` datetime(6) DEFAULT NULL,
	`artifact_safe_error_code` varchar(64) NOT NULL DEFAULT '',
	`artifact_safe_error_message` varchar(255) NOT NULL DEFAULT '',
  `safe_error_code` varchar(64) NOT NULL DEFAULT '',
  `safe_error_message` varchar(255) NOT NULL DEFAULT '',
  `version` bigint unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_appdev_provider_exec_generation` (`space_id`, `project_id`, `generation`),
  UNIQUE KEY `uk_appdev_provider_exec_idempotency` (`space_id`, `project_id`, `idempotency_key`),
  KEY `idx_appdev_provider_exec_recoverable` (`space_id`, `project_id`, `observed_state`, `desired_state`, `owner_expires_at`, `updated_at`, `id`),
  KEY `idx_appdev_provider_exec_provider_id` (`space_id`, `project_id`, `provider_key`, `provider_execution_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
