CREATE TABLE IF NOT EXISTS `scheduled_tasks` (
  `id` bigint NOT NULL,
  `space_id` bigint NOT NULL,
  `creator_id` bigint NOT NULL,
  `name` varchar(100) NOT NULL,
  `target_type` varchar(32) NOT NULL,
  `target_id` bigint NOT NULL,
  `target_name` varchar(255) NOT NULL DEFAULT '',
  `target_icon_uri` varchar(1024) NOT NULL DEFAULT '',
  `schedule_type` varchar(32) NOT NULL,
  `cron_expr` varchar(255) NOT NULL DEFAULT '',
  `timezone` varchar(64) NOT NULL,
  `run_once_at` bigint NOT NULL DEFAULT 0,
  `minute` int NOT NULL DEFAULT 0,
  `hour` int NOT NULL DEFAULT 0,
  `weekday` int NOT NULL DEFAULT 0,
  `payload` json NOT NULL,
  `keep_conversation` tinyint(1) NOT NULL DEFAULT 0,
  `conversation_id` bigint NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL,
  `execution_count` bigint NOT NULL DEFAULT 0,
  `max_executions` bigint NOT NULL DEFAULT 0,
  `latest_execution_at` bigint NOT NULL DEFAULT 0,
  `latest_execution_status` varchar(32) NOT NULL DEFAULT '',
  `next_execution_at` bigint NOT NULL DEFAULT 0,
  `lease_owner` varchar(128) NOT NULL DEFAULT '',
  `lease_expires_at` bigint NOT NULL DEFAULT 0,
  `version` bigint NOT NULL DEFAULT 1,
  `created_at` bigint NOT NULL,
  `updated_at` bigint NOT NULL,
  `deleted_at` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_scheduled_tasks_space_status_next` (`space_id`, `status`, `next_execution_at`),
  KEY `idx_scheduled_tasks_creator` (`creator_id`),
  KEY `idx_scheduled_tasks_lease` (`lease_expires_at`),
  KEY `idx_scheduled_tasks_deleted` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduled_task_executions` (
  `id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  `space_id` bigint NOT NULL,
  `trigger_type` varchar(32) NOT NULL,
  `scheduled_at` bigint NOT NULL,
  `status` varchar(32) NOT NULL,
  `attempt` int NOT NULL DEFAULT 0,
  `idempotency_key` varchar(191) NOT NULL,
  `thread_id` bigint NOT NULL DEFAULT 0,
  `run_id` bigint NOT NULL DEFAULT 0,
  `workflow_execution_id` bigint NOT NULL DEFAULT 0,
  `error_code` varchar(128) NOT NULL DEFAULT '',
  `error_message` varchar(1024) NOT NULL DEFAULT '',
  `started_at` bigint NOT NULL DEFAULT 0,
  `finished_at` bigint NOT NULL DEFAULT 0,
  `created_at` bigint NOT NULL,
  `updated_at` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scheduled_task_executions_trigger` (`task_id`, `idempotency_key`),
  KEY `idx_scheduled_task_executions_task_created` (`task_id`, `created_at`),
  KEY `idx_scheduled_task_executions_space_status` (`space_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
