CREATE TABLE IF NOT EXISTS `agent_runs` (
  `id` bigint NOT NULL,
  `thread_id` bigint NOT NULL,
  `space_id` bigint NOT NULL,
  `creator_id` bigint NOT NULL,
  `assistant_id` varchar(128) NOT NULL DEFAULT 'default',
  `status` varchar(32) NOT NULL,
  `command` json NOT NULL,
  `input` json NOT NULL,
  `config` json NOT NULL,
  `context` json NOT NULL,
  `metadata` json NOT NULL,
  `stream_mode` json NOT NULL,
  `multitask_strategy` varchar(32) NOT NULL DEFAULT 'enqueue',
  `on_disconnect` varchar(32) NOT NULL DEFAULT 'continue',
  `durability` varchar(32) NOT NULL DEFAULT 'async',
  `idempotency_key` varchar(128) DEFAULT NULL,
  `worker_id` varchar(128) NOT NULL DEFAULT '',
  `error_code` varchar(128) NOT NULL DEFAULT '',
  `error_message` text,
  `started_at` bigint NOT NULL DEFAULT 0,
  `ended_at` bigint NOT NULL DEFAULT 0,
  `created_at` bigint NOT NULL,
  `updated_at` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agent_runs_thread_created` (`thread_id`, `created_at`),
  KEY `idx_agent_runs_space_status` (`space_id`, `status`),
  UNIQUE KEY `uk_agent_runs_space_idempotency` (`space_id`, `idempotency_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
