CREATE TABLE IF NOT EXISTS `agent_artifact_scan_jobs` (
  `id` BIGINT NOT NULL,
  `thread_id` BIGINT NOT NULL,
  `run_id` BIGINT NOT NULL,
  `space_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `artifact_id` BIGINT NOT NULL,
  `file_id` BIGINT NOT NULL,
  `scanner` VARCHAR(128) NOT NULL DEFAULT '',
  `idempotency_key` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `attempt_count` INT NOT NULL DEFAULT 0,
  `last_error` TEXT NOT NULL,
  `available_at` BIGINT NOT NULL,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_artifact_scan_jobs_artifact_key` (`artifact_id`, `idempotency_key`),
  KEY `idx_agent_artifact_scan_jobs_pending` (`status`, `available_at`, `created_at`),
  KEY `idx_agent_artifact_scan_jobs_thread_created` (`thread_id`, `created_at`),
  KEY `idx_agent_artifact_scan_jobs_run_created` (`run_id`, `created_at`),
  KEY `idx_agent_artifact_scan_jobs_space_created` (`space_id`, `created_at`),
  KEY `idx_agent_artifact_scan_jobs_file` (`file_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
