CREATE TABLE IF NOT EXISTS `agent_guardrail_audit_events` (
  `id` BIGINT NOT NULL,
  `space_id` BIGINT NOT NULL,
  `thread_id` BIGINT NOT NULL,
  `run_id` BIGINT NOT NULL,
  `actor_id` BIGINT NOT NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `target_type` VARCHAR(32) NOT NULL,
  `target_id` VARCHAR(128) NOT NULL DEFAULT '',
  `operation` VARCHAR(64) NOT NULL DEFAULT '',
  `source` VARCHAR(64) NOT NULL DEFAULT '',
  `action` VARCHAR(16) NOT NULL DEFAULT '',
  `fail_mode` VARCHAR(16) NOT NULL DEFAULT '',
  `provider` VARCHAR(64) NOT NULL DEFAULT '',
  `reason_code` VARCHAR(64) NOT NULL DEFAULT '',
  `rule_ids` VARCHAR(512) NOT NULL DEFAULT '',
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agent_guardrail_audit_space_created` (`space_id`, `created_at`),
  KEY `idx_agent_guardrail_audit_thread_created` (`thread_id`, `created_at`),
  KEY `idx_agent_guardrail_audit_run_created` (`run_id`, `created_at`),
  KEY `idx_agent_guardrail_audit_actor_created` (`actor_id`, `created_at`),
  KEY `idx_agent_guardrail_audit_event_created` (`event_type`, `created_at`),
  KEY `idx_agent_guardrail_audit_target_created` (`target_type`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
