/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator. DO NOT EDIT.

package coze

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	coze "github.com/coze-dev/coze-studio/backend/api/handler/coze"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_admin := _api.Group("/admin", _adminMw()...)
			_admin.GET("/announcements", append(_listadminannouncementsMw(), coze.ListAdminAnnouncements)...)
			_announcements := _admin.Group("/announcements", _announcementsMw()...)
			_announcements.GET("/:id", append(_getadminannouncementMw(), coze.GetAdminAnnouncement)...)
			_id := _announcements.Group("/:id", _idMw()...)
			_id.GET("/audit-events", append(_listadminannouncementauditeventsMw(), coze.ListAdminAnnouncementAuditEvents)...)
			_id.POST("/cancel", append(_canceladminannouncementMw(), coze.CancelAdminAnnouncement)...)
			_id.POST("/publish", append(_publishadminannouncementMw(), coze.PublishAdminAnnouncement)...)
			_id.POST("/schedule", append(_scheduleadminannouncementMw(), coze.ScheduleAdminAnnouncement)...)
			_announcements.PUT("/:id", append(_updateadminannouncementMw(), coze.UpdateAdminAnnouncement)...)
			_announcements.POST("/replay", append(_replayadminannouncementsMw(), coze.ReplayAdminAnnouncements)...)
			_admin.POST("/announcements", append(_createadminannouncementMw(), coze.CreateAdminAnnouncement)...)
			{
				_config := _admin.Group("/config", _configMw()...)
				{
					_basic := _config.Group("/basic", _basicMw()...)
					_basic.GET("/get", append(_getbasicconfigurationMw(), coze.GetBasicConfiguration)...)
					_basic.POST("/save", append(_savebasicconfigurationMw(), coze.SaveBasicConfiguration)...)
				}
				{
					_knowledge := _config.Group("/knowledge", _knowledgeMw()...)
					_knowledge.GET("/get", append(_getknowledgeconfigMw(), coze.GetKnowledgeConfig)...)
					_knowledge.POST("/save", append(_updateknowledgeconfigMw(), coze.UpdateKnowledgeConfig)...)
				}
				{
					_model := _config.Group("/model", _modelMw()...)
					_model.POST("/create", append(_createmodelMw(), coze.CreateModel)...)
					_model.POST("/delete", append(_deletemodelMw(), coze.DeleteModel)...)
					_model.GET("/detail", append(_getmodeldetailMw(), coze.GetModelDetail)...)
					_model.GET("/grants", append(_getmodelgrantsMw(), coze.GetModelGrants)...)
					_model.POST("/grants", append(_savemodelgrantsMw(), coze.SaveModelGrants)...)
					_model.GET("/list", append(_getmodellistMw(), coze.GetModelList)...)
					_model.GET("/providers", append(_listmodelprovidersMw(), coze.ListModelProviders)...)
					_model.POST("/sort", append(_updatemodelsortMw(), coze.UpdateModelSort)...)
					_model.POST("/status", append(_updatemodelstatusMw(), coze.UpdateModelStatus)...)
					_model.POST("/test", append(_testmodelendpointMw(), coze.TestModelEndpoint)...)
					_model.POST("/update", append(_updatemodelMw(), coze.UpdateModel)...)
					{
						_manage := _model.Group("/manage", _manageMw()...)
						_manage.GET("/list", append(_listmodelsMw(), coze.ListModels)...)
					}
				}
				{
					_object_storage := _config.Group("/object-storage", _object_storageMw()...)
					_object_storage.POST("/activate", append(_activateobjectstorageconfigMw(), coze.ActivateObjectStorageConfig)...)
					_object_storage.POST("/create", append(_createobjectstorageconfigMw(), coze.CreateObjectStorageConfig)...)
					_object_storage.POST("/delete", append(_deleteobjectstorageconfigMw(), coze.DeleteObjectStorageConfig)...)
					_object_storage.GET("/list", append(_listobjectstorageconfigsMw(), coze.ListObjectStorageConfigs)...)
					_object_storage.POST("/test", append(_testobjectstorageconfigMw(), coze.TestObjectStorageConfig)...)
					_object_storage.POST("/update", append(_updateobjectstorageconfigMw(), coze.UpdateObjectStorageConfig)...)
				}
			}
		}
		{
			_app_dev := _api.Group("/app-dev", _app_devMw()...)
			{
				_spaces := _app_dev.Group("/spaces", _spacesMw()...)
				{
					_space_id := _spaces.Group("/:space_id", _space_idMw()...)
					_space_id.GET("/models", append(_listappdevmodelsMw(), coze.ListAppDevModels)...)
					_space_id.GET("/projects", append(_listappdevprojectsMw(), coze.ListAppDevProjects)...)
					_projects := _space_id.Group("/projects", _projectsMw()...)
					_projects.POST("/import", append(_importappdevprojectMw(), coze.ImportAppDevProject)...)
					_projects.DELETE("/:project_id", append(_archiveappdevprojectMw(), coze.ArchiveAppDevProject)...)
					_project_id := _projects.Group("/:project_id", _project_idMw()...)
					_project_id.GET("/build", append(_getappdevbuildstatusMw(), coze.GetAppDevBuildStatus)...)
					_project_id.POST("/build", append(_buildappdevprojectMw(), coze.BuildAppDevProject)...)
					_project_id.POST("/chat", append(_sendappdevchatmessageMw(), coze.SendAppDevChatMessage)...)
					_chat := _project_id.Group("/chat", _chatMw()...)
					_chat.POST("/cancel", append(_cancelappdevchatMw(), coze.CancelAppDevChat)...)
					_chat.GET("/events", append(_subscribeappdevchateventsMw(), coze.SubscribeAppDevChatEvents)...)
					_chat.GET("/history", append(_listappdevchathistoryMw(), coze.ListAppDevChatHistory)...)
					_chat.GET("/status", append(_getappdevchatstatusMw(), coze.GetAppDevChatStatus)...)
					_project_id.GET("/export", append(_exportappdevprojectMw(), coze.ExportAppDevProject)...)
					_project_id.DELETE("/files", append(_deleteappdevfileMw(), coze.DeleteAppDevFile)...)
					_files := _project_id.Group("/files", _filesMw()...)
					_files.GET("/content", append(_getappdevfilecontentMw(), coze.GetAppDevFileContent)...)
					_files.POST("/content", append(_saveappdevfilecontentMw(), coze.SaveAppDevFileContent)...)
					_files.POST("/rename", append(_renameappdevfileMw(), coze.RenameAppDevFile)...)
					_files.POST("/upload", append(_uploadappdevfilesMw(), coze.UploadAppDevFiles)...)
					_project_id.GET("/files", append(_listappdevfilesMw(), coze.ListAppDevFiles)...)
					_project_id.GET("/release", append(_downloadappdevreleaseMw(), coze.DownloadAppDevRelease)...)
					_project_id.GET("/snapshots", append(_listappdevsnapshotsMw(), coze.ListAppDevSnapshots)...)
					_snapshots := _project_id.Group("/snapshots", _snapshotsMw()...)
					{
						_snapshot_id := _snapshots.Group("/:snapshot_id", _snapshot_idMw()...)
						_snapshot_id.POST("/restore", append(_restoreappdevsnapshotMw(), coze.RestoreAppDevSnapshot)...)
					}
					_project_id.POST("/snapshots", append(_createappdevsnapshotMw(), coze.CreateAppDevSnapshot)...)
					{
						_runtime := _project_id.Group("/runtime", _runtimeMw()...)
						_runtime.POST("/keep-alive", append(_keepaliveappdevruntimeMw(), coze.KeepAliveAppDevRuntime)...)
						_runtime.GET("/logs", append(_listappdevruntimelogsMw(), coze.ListAppDevRuntimeLogs)...)
						_runtime.POST("/restart", append(_restartappdevruntimeMw(), coze.RestartAppDevRuntime)...)
						_runtime.POST("/start", append(_startappdevruntimeMw(), coze.StartAppDevRuntime)...)
						_runtime.GET("/status", append(_getappdevruntimestatusMw(), coze.GetAppDevRuntimeStatus)...)
						_runtime.POST("/stop", append(_stopappdevruntimeMw(), coze.StopAppDevRuntime)...)
					}
					_projects.GET("/:project_id", append(_getappdevprojectMw(), coze.GetAppDevProject)...)
					_project_id0 := _projects.Group("/:project_id", _project_id0Mw()...)
					_project_id0.POST("/duplicate", append(_duplicateappdevprojectMw(), coze.DuplicateAppDevProject)...)
					_projects.POST("/:project_id", append(_updateappdevprojectMw(), coze.UpdateAppDevProject)...)
					_space_id.POST("/projects", append(_createappdevprojectMw(), coze.CreateAppDevProject)...)
				}
			}
		}
		{
			_bot := _api.Group("/bot", _botMw()...)
			_bot.POST("/get_type_list", append(_gettypelistMw(), coze.GetTypeList)...)
			_bot.POST("/upload_file", append(_uploadfileMw(), coze.UploadFile)...)
		}
		{
			_common := _api.Group("/common", _commonMw()...)
			{
				_upload := _common.Group("/upload", _uploadMw()...)
				_upload.GET("/apply_upload_action", append(_applyuploadactionMw(), coze.ApplyUploadAction)...)
				_upload.POST("/apply_upload_action", append(_applyuploadaction0Mw(), coze.ApplyUploadAction)...)
				_upload.POST("/*tos_uri", append(_commonuploadMw(), coze.CommonUpload)...)
			}
		}
		{
			_conversation := _api.Group("/conversation", _conversationMw()...)
			_conversation.POST("/break_message", append(_breakmessageMw(), coze.BreakMessage)...)
			_conversation.POST("/chat", append(_agentrunMw(), coze.AgentRun)...)
			_conversation.POST("/clear_message", append(_clearconversationhistoryMw(), coze.ClearConversationHistory)...)
			_conversation.POST("/create_section", append(_clearconversationctxMw(), coze.ClearConversationCtx)...)
			_conversation.POST("/delete_message", append(_deletemessageMw(), coze.DeleteMessage)...)
			_conversation.POST("/get_message_list", append(_getmessagelistMw(), coze.GetMessageList)...)
		}
		{
			_developer := _api.Group("/developer", _developerMw()...)
			_developer.POST("/get_icon", append(_geticonMw(), coze.GetIcon)...)
		}
		{
			_draftbot := _api.Group("/draftbot", _draftbotMw()...)
			_draftbot.POST("/commit_check", append(_checkdraftbotcommitMw(), coze.CheckDraftBotCommit)...)
			_draftbot.POST("/create", append(_draftbotcreateMw(), coze.DraftBotCreate)...)
			_draftbot.POST("/delete", append(_deletedraftbotMw(), coze.DeleteDraftBot)...)
			_draftbot.POST("/duplicate", append(_duplicatedraftbotMw(), coze.DuplicateDraftBot)...)
			_draftbot.POST("/get_display_info", append(_getdraftbotdisplayinfoMw(), coze.GetDraftBotDisplayInfo)...)
			_draftbot.POST("/list_draft_history", append(_listdraftbothistoryMw(), coze.ListDraftBotHistory)...)
			_draftbot.POST("/publish", append(_publishdraftbotMw(), coze.PublishDraftBot)...)
			_draftbot.POST("/update_display_info", append(_updatedraftbotdisplayinfoMw(), coze.UpdateDraftBotDisplayInfo)...)
			{
				_publish := _draftbot.Group("/publish", _publishMw()...)
				{
					_connector := _publish.Group("/connector", _connectorMw()...)
					_connector.POST("/list", append(_publishconnectorlistMw(), coze.PublishConnectorList)...)
				}
			}
		}
		{
			_intelligence_api := _api.Group("/intelligence_api", _intelligence_apiMw()...)
			{
				_draft_project := _intelligence_api.Group("/draft_project", _draft_projectMw()...)
				_draft_project.POST("/copy", append(_draftprojectcopyMw(), coze.DraftProjectCopy)...)
				_draft_project.POST("/create", append(_draftprojectcreateMw(), coze.DraftProjectCreate)...)
				_draft_project.POST("/delete", append(_draftprojectdeleteMw(), coze.DraftProjectDelete)...)
				_draft_project.POST("/inner_task_list", append(_draftprojectinnertasklistMw(), coze.DraftProjectInnerTaskList)...)
				_draft_project.POST("/update", append(_draftprojectupdateMw(), coze.DraftProjectUpdate)...)
			}
			{
				_publish0 := _intelligence_api.Group("/publish", _publish0Mw()...)
				_publish0.POST("/check_version_number", append(_checkprojectversionnumberMw(), coze.CheckProjectVersionNumber)...)
				_publish0.POST("/connector_list", append(_projectpublishconnectorlistMw(), coze.ProjectPublishConnectorList)...)
				_publish0.POST("/get_published_connector", append(_getprojectpublishedconnectorMw(), coze.GetProjectPublishedConnector)...)
				_publish0.POST("/publish_project", append(_publishprojectMw(), coze.PublishProject)...)
				_publish0.POST("/publish_record_detail", append(_getpublishrecorddetailMw(), coze.GetPublishRecordDetail)...)
				_publish0.POST("/publish_record_list", append(_getpublishrecordlistMw(), coze.GetPublishRecordList)...)
			}
			{
				_search := _intelligence_api.Group("/search", _searchMw()...)
				_search.POST("/get_draft_intelligence_info", append(_getdraftintelligenceinfoMw(), coze.GetDraftIntelligenceInfo)...)
				_search.POST("/get_draft_intelligence_list", append(_getdraftintelligencelistMw(), coze.GetDraftIntelligenceList)...)
				_search.POST("/get_recently_edit_intelligence", append(_getuserrecentlyeditintelligenceMw(), coze.GetUserRecentlyEditIntelligence)...)
			}
		}
		{
			_knowledge0 := _api.Group("/knowledge", _knowledge0Mw()...)
			_knowledge0.POST("/create", append(_createdatasetMw(), coze.CreateDataset)...)
			_knowledge0.POST("/delete", append(_deletedatasetMw(), coze.DeleteDataset)...)
			_knowledge0.POST("/detail", append(_datasetdetailMw(), coze.DatasetDetail)...)
			_knowledge0.POST("/list", append(_listdatasetMw(), coze.ListDataset)...)
			_knowledge0.POST("/update", append(_updatedatasetMw(), coze.UpdateDataset)...)
			{
				_document := _knowledge0.Group("/document", _documentMw()...)
				_document.POST("/create", append(_createdocumentMw(), coze.CreateDocument)...)
				_document.POST("/delete", append(_deletedocumentMw(), coze.DeleteDocument)...)
				_document.POST("/list", append(_listdocumentMw(), coze.ListDocument)...)
				_document.POST("/resegment", append(_resegmentMw(), coze.Resegment)...)
				_document.POST("/update", append(_updatedocumentMw(), coze.UpdateDocument)...)
				{
					_progress := _document.Group("/progress", _progressMw()...)
					_progress.POST("/get", append(_getdocumentprogressMw(), coze.GetDocumentProgress)...)
				}
			}
			{
				_icon := _knowledge0.Group("/icon", _iconMw()...)
				_icon.POST("/get", append(_geticonfordatasetMw(), coze.GetIconForDataset)...)
			}
			{
				_photo := _knowledge0.Group("/photo", _photoMw()...)
				_photo.POST("/caption", append(_updatephotocaptionMw(), coze.UpdatePhotoCaption)...)
				_photo.POST("/detail", append(_photodetailMw(), coze.PhotoDetail)...)
				_photo.POST("/extract_caption", append(_extractphotocaptionMw(), coze.ExtractPhotoCaption)...)
				_photo.POST("/list", append(_listphotoMw(), coze.ListPhoto)...)
			}
			{
				_review := _knowledge0.Group("/review", _reviewMw()...)
				_review.POST("/create", append(_createdocumentreviewMw(), coze.CreateDocumentReview)...)
				_review.POST("/mget", append(_mgetdocumentreviewMw(), coze.MGetDocumentReview)...)
				_review.POST("/save", append(_savedocumentreviewMw(), coze.SaveDocumentReview)...)
			}
			{
				_slice := _knowledge0.Group("/slice", _sliceMw()...)
				_slice.POST("/create", append(_createsliceMw(), coze.CreateSlice)...)
				_slice.POST("/delete", append(_deletesliceMw(), coze.DeleteSlice)...)
				_slice.POST("/list", append(_listsliceMw(), coze.ListSlice)...)
				_slice.POST("/update", append(_updatesliceMw(), coze.UpdateSlice)...)
			}
			{
				_table_schema := _knowledge0.Group("/table_schema", _table_schemaMw()...)
				_table_schema.POST("/get", append(_gettableschemaMw(), coze.GetTableSchema)...)
				_table_schema.POST("/validate", append(_validatetableschemaMw(), coze.ValidateTableSchema)...)
			}
		}
		{
			_marketplace := _api.Group("/marketplace", _marketplaceMw()...)
			{
				_product := _marketplace.Group("/product", _productMw()...)
				_product.GET("/call_info", append(_publicgetproductcallinfoMw(), coze.PublicGetProductCallInfo)...)
				_product.GET("/config", append(_publicgetmarketpluginconfigMw(), coze.PublicGetMarketPluginConfig)...)
				_product.GET("/detail", append(_publicgetproductdetailMw(), coze.PublicGetProductDetail)...)
				_product.POST("/duplicate", append(_publicduplicateproductMw(), coze.PublicDuplicateProduct)...)
				_product.POST("/favorite", append(_publicfavoriteproductMw(), coze.PublicFavoriteProduct)...)
				_favorite := _product.Group("/favorite", _favoriteMw()...)
				_favorite.GET("/list.v2", append(_publicgetuserfavoritelistv2Mw(), coze.PublicGetUserFavoriteListV2)...)
				_product.GET("/list", append(_publicgetproductlistMw(), coze.PublicGetProductList)...)
				_product.GET("/search", append(_publicsearchproductMw(), coze.PublicSearchProduct)...)
				_search0 := _product.Group("/search", _search0Mw()...)
				_search0.GET("/suggest", append(_publicsearchsuggestMw(), coze.PublicSearchSuggest)...)
				{
					_category := _product.Group("/category", _categoryMw()...)
					_category.GET("/list", append(_publicgetproductcategorylistMw(), coze.PublicGetProductCategoryList)...)
				}
			}
		}
		{
			_memory := _api.Group("/memory", _memoryMw()...)
			_memory.GET("/doc_table_info", append(_getdocumenttableinfoMw(), coze.GetDocumentTableInfo)...)
			_memory.GET("/sys_variable_conf", append(_getsysvariableconfMw(), coze.GetSysVariableConf)...)
			_memory.GET("/table_mode_config", append(_getmodeconfigMw(), coze.GetModeConfig)...)
			{
				_database := _memory.Group("/database", _databaseMw()...)
				_database.POST("/add", append(_adddatabaseMw(), coze.AddDatabase)...)
				_database.POST("/bind_to_bot", append(_binddatabaseMw(), coze.BindDatabase)...)
				_database.POST("/delete", append(_deletedatabaseMw(), coze.DeleteDatabase)...)
				_database.POST("/get_by_id", append(_getdatabasebyidMw(), coze.GetDatabaseByID)...)
				_database.POST("/get_connector_name", append(_getconnectornameMw(), coze.GetConnectorName)...)
				_database.POST("/get_online_database_id", append(_getonlinedatabaseidMw(), coze.GetOnlineDatabaseId)...)
				_database.POST("/get_template", append(_getdatabasetemplateMw(), coze.GetDatabaseTemplate)...)
				_database.POST("/list", append(_listdatabaseMw(), coze.ListDatabase)...)
				_database.POST("/list_records", append(_listdatabaserecordsMw(), coze.ListDatabaseRecords)...)
				_database.POST("/unbind_to_bot", append(_unbinddatabaseMw(), coze.UnBindDatabase)...)
				_database.POST("/update", append(_updatedatabaseMw(), coze.UpdateDatabase)...)
				_database.POST("/update_bot_switch", append(_updatedatabasebotswitchMw(), coze.UpdateDatabaseBotSwitch)...)
				_database.POST("/update_records", append(_updatedatabaserecordsMw(), coze.UpdateDatabaseRecords)...)
				{
					_table := _database.Group("/table", _tableMw()...)
					_table.POST("/list_new", append(_getbotdatabaseMw(), coze.GetBotDatabase)...)
					_table.POST("/reset", append(_resetbottableMw(), coze.ResetBotTable)...)
				}
			}
			{
				_project := _memory.Group("/project", _projectMw()...)
				{
					_variable := _project.Group("/variable", _variableMw()...)
					_variable.GET("/meta_list", append(_getprojectvariablelistMw(), coze.GetProjectVariableList)...)
					_variable.POST("/meta_update", append(_updateprojectvariableMw(), coze.UpdateProjectVariable)...)
				}
			}
			{
				_table_file := _memory.Group("/table_file", _table_fileMw()...)
				_table_file.POST("/get_progress", append(_databasefileprogressdataMw(), coze.DatabaseFileProgressData)...)
				_table_file.POST("/submit", append(_submitdatabaseinserttaskMw(), coze.SubmitDatabaseInsertTask)...)
			}
			{
				_table_schema0 := _memory.Group("/table_schema", _table_schema0Mw()...)
				_table_schema0.POST("/get", append(_getdatabasetableschemaMw(), coze.GetDatabaseTableSchema)...)
				_table_schema0.POST("/validate", append(_validatedatabasetableschemaMw(), coze.ValidateDatabaseTableSchema)...)
			}
			{
				_variable0 := _memory.Group("/variable", _variable0Mw()...)
				_variable0.POST("/delete", append(_delprofilememoryMw(), coze.DelProfileMemory)...)
				_variable0.POST("/get", append(_getplaygroundmemoryMw(), coze.GetPlayGroundMemory)...)
				_variable0.POST("/get_meta", append(_getmemoryvariablemetaMw(), coze.GetMemoryVariableMeta)...)
				_variable0.POST("/upsert", append(_setkvmemoryMw(), coze.SetKvMemory)...)
			}
		}
		{
			_oauth := _api.Group("/oauth", _oauthMw()...)
			_oauth.GET("/authorization_code", append(_oauthauthorizationcodeMw(), coze.OauthAuthorizationCode)...)
		}
		{
			_passport := _api.Group("/passport", _passportMw()...)
			{
				_account := _passport.Group("/account", _accountMw()...)
				{
					_info := _account.Group("/info", _infoMw()...)
					{
						_v2 := _info.Group("/v2", _v2Mw()...)
						_v2.POST("/", append(_passportaccountinfov2Mw(), coze.PassportAccountInfoV2)...)
					}
				}
			}
			{
				_web := _passport.Group("/web", _webMw()...)
				{
					_email := _web.Group("/email", _emailMw()...)
					{
						_login := _email.Group("/login", _loginMw()...)
						_login.POST("/", append(_passportwebemailloginpostMw(), coze.PassportWebEmailLoginPost)...)
					}
					{
						_password := _email.Group("/password", _passwordMw()...)
						{
							_reset := _password.Group("/reset", _resetMw()...)
							_reset.GET("/", append(_passportwebemailpasswordresetgetMw(), coze.PassportWebEmailPasswordResetGet)...)
						}
					}
					{
						_register := _email.Group("/register", _registerMw()...)
						{
							_v20 := _register.Group("/v2", _v20Mw()...)
							_v20.POST("/", append(_passportwebemailregisterv2postMw(), coze.PassportWebEmailRegisterV2Post)...)
						}
					}
				}
				{
					_logout := _web.Group("/logout", _logoutMw()...)
					_logout.GET("/", append(_passportweblogoutgetMw(), coze.PassportWebLogoutGet)...)
				}
			}
		}
		{
			_permission_api := _api.Group("/permission_api", _permission_apiMw()...)
			{
				_coze_web_app := _permission_api.Group("/coze_web_app", _coze_web_appMw()...)
				_coze_web_app.POST("/impersonate_coze_user", append(_impersonatecozeuserMw(), coze.ImpersonateCozeUser)...)
			}
			{
				_pat := _permission_api.Group("/pat", _patMw()...)
				_pat.POST("/create_personal_access_token_and_permission", append(_createpersonalaccesstokenandpermissionMw(), coze.CreatePersonalAccessTokenAndPermission)...)
				_pat.POST("/delete_personal_access_token_and_permission", append(_deletepersonalaccesstokenandpermissionMw(), coze.DeletePersonalAccessTokenAndPermission)...)
				_pat.GET("/get_personal_access_token_and_permission", append(_getpersonalaccesstokenandpermissionMw(), coze.GetPersonalAccessTokenAndPermission)...)
				_pat.GET("/list_personal_access_tokens", append(_listpersonalaccesstokensMw(), coze.ListPersonalAccessTokens)...)
				_pat.POST("/update_personal_access_token_and_permission", append(_updatepersonalaccesstokenandpermissionMw(), coze.UpdatePersonalAccessTokenAndPermission)...)
			}
		}
		{
			_playground := _api.Group("/playground", _playgroundMw()...)
			_playground.POST("/get_onboarding", append(_getonboardingMw(), coze.GetOnboarding)...)
			{
				_upload0 := _playground.Group("/upload", _upload0Mw()...)
				_upload0.POST("/auth_token", append(_getuploadauthtokenMw(), coze.GetUploadAuthToken)...)
			}
		}
		{
			_playground_api := _api.Group("/playground_api", _playground_apiMw()...)
			_playground_api.POST("/create_update_shortcut_command", append(_createupdateshortcutcommandMw(), coze.CreateUpdateShortcutCommand)...)
			_playground_api.POST("/delete_prompt_resource", append(_deletepromptresourceMw(), coze.DeletePromptResource)...)
			_playground_api.POST("/get_file_list", append(_getfileurlsMw(), coze.GetFileUrls)...)
			_playground_api.POST("/get_imagex_url", append(_getimagexshorturlMw(), coze.GetImagexShortUrl)...)
			_playground_api.POST("/get_official_prompt_list", append(_getofficialpromptresourcelistMw(), coze.GetOfficialPromptResourceList)...)
			_playground_api.GET("/get_prompt_resource_info", append(_getpromptresourceinfoMw(), coze.GetPromptResourceInfo)...)
			_playground_api.POST("/mget_user_info", append(_mgetuserbasicinfoMw(), coze.MGetUserBasicInfo)...)
			_playground_api.POST("/report_user_behavior", append(_reportuserbehaviorMw(), coze.ReportUserBehavior)...)
			_playground_api.POST("/upsert_prompt_resource", append(_upsertpromptresourceMw(), coze.UpsertPromptResource)...)
			{
				_draftbot0 := _playground_api.Group("/draftbot", _draftbot0Mw()...)
				_draftbot0.POST("/get_draft_bot_info", append(_getdraftbotinfoagwMw(), coze.GetDraftBotInfoAgw)...)
				_draftbot0.POST("/update_draft_bot_info", append(_updatedraftbotinfoagwMw(), coze.UpdateDraftBotInfoAgw)...)
			}
			{
				_notice := _playground_api.Group("/notice", _noticeMw()...)
				_notice.POST("/get_list", append(_getnoticelistMw(), coze.GetNoticeList)...)
				_notice.POST("/get_unread_count", append(_getnoticeunreadcountMw(), coze.GetNoticeUnreadCount)...)
				_notice.POST("/mark_read", append(_noticemarkreadMw(), coze.NoticeMarkRead)...)
			}
			{
				_operate := _playground_api.Group("/operate", _operateMw()...)
				_operate.POST("/get_bot_popup_info", append(_getbotpopupinfoMw(), coze.GetBotPopupInfo)...)
				_operate.POST("/update_bot_popup_info", append(_updatebotpopupinfoMw(), coze.UpdateBotPopupInfo)...)
			}
			{
				_space := _playground_api.Group("/space", _spaceMw()...)
				_space.POST("/list", append(_getspacelistv2Mw(), coze.GetSpaceListV2)...)
			}
		}
		{
			_plugin := _api.Group("/plugin", _pluginMw()...)
			_plugin.POST("/get_oauth_schema", append(_getoauthschemaMw(), coze.GetOAuthSchema)...)
			{
				_oauth0 := _plugin.Group("/oauth", _oauth0Mw()...)
				_oauth0.POST("/confirm", append(_pluginoauthconfirmMw(), coze.PluginOauthConfirm)...)
				_oauth0.GET("/get_oauth_info", append(_pluginoauthinfoMw(), coze.PluginOauthInfo)...)
			}
		}
		{
			_plugin_api := _api.Group("/plugin_api", _plugin_apiMw()...)
			_plugin_api.POST("/batch_create_api", append(_batchcreateapiMw(), coze.BatchCreateAPI)...)
			_plugin_api.POST("/check_and_lock_plugin_edit", append(_checkandlockplugineditMw(), coze.CheckAndLockPluginEdit)...)
			_plugin_api.POST("/convert_to_openapi", append(_convert2openapiMw(), coze.Convert2OpenAPI)...)
			_plugin_api.POST("/create_api", append(_createapiMw(), coze.CreateAPI)...)
			_plugin_api.POST("/debug_api", append(_debugapiMw(), coze.DebugAPI)...)
			_plugin_api.POST("/debug_code_plugin", append(_debugcodepluginMw(), coze.DebugCodePlugin)...)
			_plugin_api.POST("/del_plugin", append(_delpluginMw(), coze.DelPlugin)...)
			_plugin_api.POST("/delete_api", append(_deleteapiMw(), coze.DeleteAPI)...)
			_plugin_api.POST("/get_bot_default_params", append(_getbotdefaultparamsMw(), coze.GetBotDefaultParams)...)
			_plugin_api.POST("/get_code_plugin_draft", append(_getcodeplugindraftMw(), coze.GetCodePluginDraft)...)
			_plugin_api.POST("/get_code_plugin_version", append(_getcodepluginversionMw(), coze.GetCodePluginVersion)...)
			_plugin_api.POST("/get_dev_plugin_list", append(_getdevpluginlistMw(), coze.GetDevPluginList)...)
			_plugin_api.POST("/get_oauth_schema", append(_getoauthschemaapiMw(), coze.GetOAuthSchemaAPI)...)
			_plugin_api.POST("/get_oauth_status", append(_getoauthstatusMw(), coze.GetOAuthStatus)...)
			_plugin_api.POST("/get_playground_plugin_list", append(_getplaygroundpluginlistMw(), coze.GetPlaygroundPluginList)...)
			_plugin_api.POST("/get_plugin_apis", append(_getpluginapisMw(), coze.GetPluginAPIs)...)
			_plugin_api.POST("/get_plugin_info", append(_getplugininfoMw(), coze.GetPluginInfo)...)
			_plugin_api.POST("/get_plugin_next_version", append(_getpluginnextversionMw(), coze.GetPluginNextVersion)...)
			_plugin_api.POST("/get_queried_oauth_plugins", append(_getqueriedoauthpluginlistMw(), coze.GetQueriedOAuthPluginList)...)
			_plugin_api.POST("/get_updated_apis", append(_getupdatedapisMw(), coze.GetUpdatedAPIs)...)
			_plugin_api.POST("/get_user_authority", append(_getuserauthorityMw(), coze.GetUserAuthority)...)
			_plugin_api.POST("/library_resource_list", append(_libraryresourcelistMw(), coze.LibraryResourceList)...)
			_plugin_api.POST("/project_resource_list", append(_projectresourcelistMw(), coze.ProjectResourceList)...)
			_plugin_api.POST("/publish_plugin", append(_publishpluginMw(), coze.PublishPlugin)...)
			_plugin_api.POST("/register", append(_registerpluginMw(), coze.RegisterPlugin)...)
			_plugin_api.POST("/register_plugin_meta", append(_registerpluginmetaMw(), coze.RegisterPluginMeta)...)
			_plugin_api.POST("/resource_copy_cancel", append(_resourcecopycancelMw(), coze.ResourceCopyCancel)...)
			_plugin_api.POST("/resource_copy_detail", append(_resourcecopydetailMw(), coze.ResourceCopyDetail)...)
			_plugin_api.POST("/resource_copy_dispatch", append(_resourcecopydispatchMw(), coze.ResourceCopyDispatch)...)
			_plugin_api.POST("/resource_copy_retry", append(_resourcecopyretryMw(), coze.ResourceCopyRetry)...)
			_plugin_api.POST("/revoke_auth_token", append(_revokeauthtokenMw(), coze.RevokeAuthToken)...)
			_plugin_api.POST("/save_code_plugin_draft", append(_savecodeplugindraftMw(), coze.SaveCodePluginDraft)...)
			_plugin_api.POST("/unlock_plugin_edit", append(_unlockplugineditMw(), coze.UnlockPluginEdit)...)
			_plugin_api.POST("/update", append(_updatepluginMw(), coze.UpdatePlugin)...)
			_plugin_api.POST("/update_api", append(_updateapiMw(), coze.UpdateAPI)...)
			_plugin_api.POST("/update_bot_default_params", append(_updatebotdefaultparamsMw(), coze.UpdateBotDefaultParams)...)
			_plugin_api.POST("/update_plugin_meta", append(_updatepluginmetaMw(), coze.UpdatePluginMeta)...)
		}
		{
			_plugin_oauth := _api.Group("/plugin_oauth", _plugin_oauthMw()...)
			{
				_plugin_id := _plugin_oauth.Group("/:plugin_id", _plugin_idMw()...)
				_plugin_id.GET("/authorization_code", append(_pluginoauthauthorizationcodeMw(), coze.PluginOauthAuthorizationCode)...)
			}
		}
		{
			_user := _api.Group("/user", _userMw()...)
			_user.POST("/update_profile", append(_userupdateprofileMw(), coze.UserUpdateProfile)...)
			_user.POST("/update_profile_check", append(_updateuserprofilecheckMw(), coze.UpdateUserProfileCheck)...)
		}
		{
			_web0 := _api.Group("/web", _web0Mw()...)
			{
				_user0 := _web0.Group("/user", _user0Mw()...)
				{
					_update := _user0.Group("/update", _updateMw()...)
					{
						_upload_avatar := _update.Group("/upload_avatar", _upload_avatarMw()...)
						_upload_avatar.POST("/", append(_userupdateavatarMw(), coze.UserUpdateAvatar)...)
					}
				}
			}
		}
		{
			_workbench := _api.Group("/workbench", _workbenchMw()...)
			_workbench.GET("/models", append(_listworkspacemodelsMw(), coze.ListWorkspaceModels)...)
			_models := _workbench.Group("/models", _modelsMw()...)
			_models.DELETE("/:model_id", append(_deleteworkspacemodelMw(), coze.DeleteWorkspaceModel)...)
			_models.GET("/:model_id", append(_getworkspacemodelMw(), coze.GetWorkspaceModel)...)
			_model_id := _models.Group("/:model_id", _model_idMw()...)
			_model_id.POST("/status", append(_setworkspacemodelstatusMw(), coze.SetWorkspaceModelStatus)...)
			_models.POST("/test", append(_testworkspacemodelMw(), coze.TestWorkspaceModel)...)
			_workbench.POST("/models", append(_upsertworkspacemodelMw(), coze.UpsertWorkspaceModel)...)
			_workbench.GET("/runtime_doctor", append(_getworkbenchruntimedoctorMw(), coze.GetWorkbenchRuntimeDoctor)...)
			_workbench.GET("/scheduled_task_cron_presets", append(_listscheduledtaskcronpresetsMw(), coze.ListScheduledTaskCronPresets)...)
			_workbench.GET("/scheduled_task_targets", append(_listscheduledtasktargetsMw(), coze.ListScheduledTaskTargets)...)
			_workbench.GET("/scheduled_tasks", append(_listscheduledtasksMw(), coze.ListScheduledTasks)...)
			_scheduled_tasks := _workbench.Group("/scheduled_tasks", _scheduled_tasksMw()...)
			_scheduled_tasks.DELETE("/:task_id", append(_deletescheduledtaskMw(), coze.DeleteScheduledTask)...)
			_task_id := _scheduled_tasks.Group("/:task_id", _task_idMw()...)
			_task_id.POST("/disable", append(_disablescheduledtaskMw(), coze.DisableScheduledTask)...)
			_task_id.POST("/enable", append(_enablescheduledtaskMw(), coze.EnableScheduledTask)...)
			_task_id.POST("/execute", append(_executescheduledtaskMw(), coze.ExecuteScheduledTask)...)
			_task_id.GET("/executions", append(_listscheduledtaskexecutionsMw(), coze.ListScheduledTaskExecutions)...)
			_scheduled_tasks.GET("/:task_id", append(_getscheduledtaskMw(), coze.GetScheduledTask)...)
			_scheduled_tasks.PUT("/:task_id", append(_updatescheduledtaskMw(), coze.UpdateScheduledTask)...)
			_workbench.POST("/scheduled_tasks", append(_createscheduledtaskMw(), coze.CreateScheduledTask)...)
			_workbench.GET("/skills", append(_listskillsMw(), coze.ListSkills)...)
			_skills := _workbench.Group("/skills", _skillsMw()...)
			_skills.DELETE("/:skill_id", append(_deleteskillMw(), coze.DeleteSkill)...)
			_skill_id := _skills.Group("/:skill_id", _skill_idMw()...)
			_skill_id.GET("/export", append(_exportskillMw(), coze.ExportSkill)...)
			_skill_id.POST("/test_run", append(_testrunskillMw(), coze.TestRunSkill)...)
			_skill_id.GET("/versions", append(_listskillversionsMw(), coze.ListSkillVersions)...)
			_versions := _skill_id.Group("/versions", _versionsMw()...)
			{
				_version_id := _versions.Group("/:version_id", _version_idMw()...)
				_version_id.PUT("/content", append(_updateskillversioncontentMw(), coze.UpdateSkillVersionContent)...)
				_version_id.GET("/export", append(_exportskillversionMw(), coze.ExportSkillVersion)...)
				_version_id.GET("/resources", append(_listskillversionresourcesMw(), coze.ListSkillVersionResources)...)
				_version_id.PUT("/resources", append(_updateskillversionresourceMw(), coze.UpdateSkillVersionResource)...)
				_version_id.POST("/rollback", append(_rollbackskillversionMw(), coze.RollbackSkillVersion)...)
			}
			_skills.GET("/:skill_id", append(_getskillMw(), coze.GetSkill)...)
			_skills.GET("/tool_candidates", append(_listskilltoolcandidatesMw(), coze.ListSkillToolCandidates)...)
			_workbench.POST("/skills", append(_createskillMw(), coze.CreateSkill)...)
			_skills0 := _workbench.Group("/skills", _skills0Mw()...)
			_skills0.PUT("/:id", append(_updateskillMw(), coze.UpdateSkill)...)
			_skills0.POST("/import", append(_importskillMw(), coze.ImportSkill)...)
			_skills0.POST("/install", append(_installskillfromartifactMw(), coze.InstallSkillFromArtifact)...)
			_workbench.GET("/task_threads", append(_listtaskthreadsMw(), coze.ListTaskThreads)...)
			_task_threads := _workbench.Group("/task_threads", _task_threadsMw()...)
			_task_threads.GET("/:thread_id", append(_gettaskthreadMw(), coze.GetTaskThread)...)
			_thread_id := _task_threads.Group("/:thread_id", _thread_idMw()...)
			_thread_id.GET("/artifacts", append(_listtaskthreadartifactsMw(), coze.ListTaskThreadArtifacts)...)
			_artifacts := _thread_id.Group("/artifacts", _artifactsMw()...)
			{
				_artifact_id := _artifacts.Group("/:artifact_id", _artifact_idMw()...)
				_artifact_id.GET("/signed_url", append(_gettaskthreadartifactsignedurlMw(), coze.GetTaskThreadArtifactSignedURL)...)
			}
			_thread_id.GET("/guardrail_audit_events", append(_listtaskthreadguardrailauditeventsMw(), coze.ListTaskThreadGuardrailAuditEvents)...)
			_guardrail_audit_events := _thread_id.Group("/guardrail_audit_events", _guardrail_audit_eventsMw()...)
			_guardrail_audit_events.GET("/export", append(_exporttaskthreadguardrailauditeventsMw(), coze.ExportTaskThreadGuardrailAuditEvents)...)
			_thread_id.GET("/mcp_runtime_audit_events", append(_listtaskthreadmcpruntimeauditeventsMw(), coze.ListTaskThreadMCPRuntimeAuditEvents)...)
			_thread_id.GET("/memories", append(_listtaskthreadmemoriesMw(), coze.ListTaskThreadMemories)...)
			_memories := _thread_id.Group("/memories", _memoriesMw()...)
			_memories.GET("/audit_events", append(_listtaskthreadmemoryauditeventsMw(), coze.ListTaskThreadMemoryAuditEvents)...)
			_memories.POST("/clear", append(_cleartaskthreadmemoriesMw(), coze.ClearTaskThreadMemories)...)
			_memories.GET("/export", append(_exporttaskthreadmemoriesMw(), coze.ExportTaskThreadMemories)...)
			_memories.POST("/import", append(_importtaskthreadmemoriesMw(), coze.ImportTaskThreadMemories)...)
			_memories.DELETE("/:memory_id", append(_deletetaskthreadmemoryMw(), coze.DeleteTaskThreadMemory)...)
			_memory_id := _memories.Group("/:memory_id", _memory_idMw()...)
			_memory_id.POST("/restore", append(_restoretaskthreadmemoryMw(), coze.RestoreTaskThreadMemory)...)
			_memories.PUT("/:memory_id", append(_updatetaskthreadmemoryMw(), coze.UpdateTaskThreadMemory)...)
			_thread_id.GET("/messages", append(_listtaskthreadmessagesMw(), coze.ListTaskThreadMessages)...)
			_thread_id.POST("/messages", append(_appendtaskthreadmessageMw(), coze.AppendTaskThreadMessage)...)
			_thread_id.GET("/run_events", append(_listtaskthreadruneventsMw(), coze.ListTaskThreadRunEvents)...)
			_thread_id.GET("/runs", append(_listtaskthreadrunsMw(), coze.ListTaskThreadRuns)...)
			_runs := _thread_id.Group("/runs", _runsMw()...)
			{
				_run_id := _runs.Group("/:run_id", _run_idMw()...)
				_run_id.POST("/cancel", append(_canceltaskthreadrunMw(), coze.CancelTaskThreadRun)...)
				_run_id.POST("/resume", append(_resumetaskthreadrunMw(), coze.ResumeTaskThreadRun)...)
				_run_id.POST("/retry", append(_retrytaskthreadsubagentrunMw(), coze.RetryTaskThreadSubagentRun)...)
			}
			_thread_id.POST("/runs", append(_createtaskthreadrunMw(), coze.CreateTaskThreadRun)...)
			_thread_id.POST("/suggestions", append(_generatetaskthreadsuggestionsMw(), coze.GenerateTaskThreadSuggestions)...)
			_thread_id.GET("/token_usage", append(_gettaskthreadtokenusageMw(), coze.GetTaskThreadTokenUsage)...)
			_workbench.POST("/task_threads", append(_createtaskthreadMw(), coze.CreateTaskThread)...)
			_workbench.POST("/threads", append(_createcanonicalthreadMw(), coze.CreateCanonicalThread)...)
			_threads := _workbench.Group("/threads", _threadsMw()...)
			_threads.POST("/search", append(_searchcanonicalthreadsMw(), coze.SearchCanonicalThreads)...)
			_threads.DELETE("/:thread_id", append(_deletecanonicalthreadMw(), coze.DeleteCanonicalThread)...)
			_thread_id0 := _threads.Group("/:thread_id", _thread_id0Mw()...)
			_thread_id0.GET("/history", append(_getcanonicalthreadhistoryMw(), coze.GetCanonicalThreadHistory)...)
			_thread_id0.POST("/history", append(_postcanonicalthreadhistoryMw(), coze.PostCanonicalThreadHistory)...)
			_thread_id0.GET("/messages", append(_listcanonicalthreadmessagesMw(), coze.ListCanonicalThreadMessages)...)
			_thread_id0.GET("/runs", append(_listcanonicalrunsMw(), coze.ListCanonicalRuns)...)
			_runs0 := _thread_id0.Group("/runs", _runs0Mw()...)
			_runs0.GET("/:run_id", append(_getcanonicalrunMw(), coze.GetCanonicalRun)...)
			_run_id0 := _runs0.Group("/:run_id", _run_id0Mw()...)
			_run_id0.POST("/cancel", append(_cancelcanonicalrunMw(), coze.CancelCanonicalRun)...)
			_run_id0.GET("/events", append(_listcanonicalruneventsMw(), coze.ListCanonicalRunEvents)...)
			_run_id0.GET("/join", append(_joincanonicalrunMw(), coze.JoinCanonicalRun)...)
			_run_id0.GET("/messages", append(_listcanonicalrunmessagesMw(), coze.ListCanonicalRunMessages)...)
			_run_id0.POST("/resume", append(_resumecanonicalrunMw(), coze.ResumeCanonicalRun)...)
			_run_id0.GET("/stream", append(_reconnectcanonicalrunstreamMw(), coze.ReconnectCanonicalRunStream)...)
			_runs0.POST("/stream", append(_streamcanonicalrunMw(), coze.StreamCanonicalRun)...)
			_runs0.POST("/wait", append(_waitcanonicalrunMw(), coze.WaitCanonicalRun)...)
			_thread_id0.POST("/runs", append(_createcanonicalrunMw(), coze.CreateCanonicalRun)...)
			_thread_id0.GET("/state", append(_getcanonicalthreadstateMw(), coze.GetCanonicalThreadState)...)
			_thread_id0.POST("/state", append(_updatecanonicalthreadstateMw(), coze.UpdateCanonicalThreadState)...)
			_threads.GET("/:thread_id", append(_getcanonicalthreadMw(), coze.GetCanonicalThread)...)
			_threads.PATCH("/:thread_id", append(_patchcanonicalthreadMw(), coze.PatchCanonicalThread)...)
		}
		{
			_workflow_api := _api.Group("/workflow_api", _workflow_apiMw()...)
			_workflow_api.GET("/apiDetail", append(_getapidetailMw(), coze.GetApiDetail)...)
			_workflow_api.POST("/batch_delete", append(_batchdeleteworkflowMw(), coze.BatchDeleteWorkflow)...)
			_workflow_api.POST("/cancel", append(_cancelworkflowMw(), coze.CancelWorkFlow)...)
			_workflow_api.POST("/canvas", append(_getcanvasinfoMw(), coze.GetCanvasInfo)...)
			_workflow_api.POST("/copy", append(_copyworkflowMw(), coze.CopyWorkflow)...)
			_workflow_api.POST("/copy_wk_template", append(_copywktemplateapiMw(), coze.CopyWkTemplateApi)...)
			_workflow_api.POST("/create", append(_createworkflowMw(), coze.CreateWorkflow)...)
			_workflow_api.POST("/delete", append(_deleteworkflowMw(), coze.DeleteWorkflow)...)
			_workflow_api.POST("/delete_strategy", append(_getdeletestrategyMw(), coze.GetDeleteStrategy)...)
			_workflow_api.POST("/example_workflow_list", append(_getexampleworkflowlistMw(), coze.GetExampleWorkFlowList)...)
			_workflow_api.GET("/get_node_execute_history", append(_getnodeexecutehistoryMw(), coze.GetNodeExecuteHistory)...)
			_workflow_api.GET("/get_process", append(_getworkflowprocessMw(), coze.GetWorkFlowProcess)...)
			_workflow_api.POST("/get_trace", append(_gettracesdkMw(), coze.GetTraceSDK)...)
			_workflow_api.POST("/history_schema", append(_gethistoryschemaMw(), coze.GetHistorySchema)...)
			_workflow_api.POST("/list_publish_workflow", append(_listpublishworkflowMw(), coze.ListPublishWorkflow)...)
			_workflow_api.POST("/list_spans", append(_listrootspansMw(), coze.ListRootSpans)...)
			_workflow_api.POST("/llm_fc_setting_detail", append(_getllmnodefcsettingdetailMw(), coze.GetLLMNodeFCSettingDetail)...)
			_workflow_api.POST("/llm_fc_setting_merged", append(_getllmnodefcsettingsmergedMw(), coze.GetLLMNodeFCSettingsMerged)...)
			_workflow_api.POST("/nodeDebug", append(_workflownodedebugv2Mw(), coze.WorkflowNodeDebugV2)...)
			_workflow_api.POST("/node_panel_search", append(_nodepanelsearchMw(), coze.NodePanelSearch)...)
			_workflow_api.POST("/node_template_list", append(_nodetemplatelistMw(), coze.NodeTemplateList)...)
			_workflow_api.POST("/node_type", append(_queryworkflownodetypesMw(), coze.QueryWorkflowNodeTypes)...)
			_workflow_api.POST("/publish", append(_publishworkflowMw(), coze.PublishWorkflow)...)
			_workflow_api.POST("/released_workflows", append(_getreleasedworkflowsMw(), coze.GetReleasedWorkflows)...)
			_workflow_api.POST("/save", append(_saveworkflowMw(), coze.SaveWorkflow)...)
			_workflow_api.POST("/sign_image_url", append(_signimageurlMw(), coze.SignImageURL)...)
			_workflow_api.POST("/test_resume", append(_workflowtestresumeMw(), coze.WorkFlowTestResume)...)
			_workflow_api.POST("/test_run", append(_workflowtestrunMw(), coze.WorkFlowTestRun)...)
			_workflow_api.POST("/update_meta", append(_updateworkflowmetaMw(), coze.UpdateWorkflowMeta)...)
			_workflow_api.POST("/validate_tree", append(_validatetreeMw(), coze.ValidateTree)...)
			_workflow_api.POST("/workflow_detail", append(_getworkflowdetailMw(), coze.GetWorkflowDetail)...)
			_workflow_api.POST("/workflow_detail_info", append(_getworkflowdetailinfoMw(), coze.GetWorkflowDetailInfo)...)
			_workflow_api.POST("/workflow_list", append(_getworkflowlistMw(), coze.GetWorkFlowList)...)
			_workflow_api.POST("/workflow_references", append(_getworkflowreferencesMw(), coze.GetWorkflowReferences)...)
			{
				_chat_flow_role := _workflow_api.Group("/chat_flow_role", _chat_flow_roleMw()...)
				_chat_flow_role.POST("/create", append(_createchatflowroleMw(), coze.CreateChatFlowRole)...)
				_chat_flow_role.POST("/delete", append(_deletechatflowroleMw(), coze.DeleteChatFlowRole)...)
				_chat_flow_role.GET("/get", append(_getchatflowroleMw(), coze.GetChatFlowRole)...)
			}
			{
				_project_conversation := _workflow_api.Group("/project_conversation", _project_conversationMw()...)
				_project_conversation.POST("/create", append(_createprojectconversationdefMw(), coze.CreateProjectConversationDef)...)
				_project_conversation.POST("/delete", append(_deleteprojectconversationdefMw(), coze.DeleteProjectConversationDef)...)
				_project_conversation.GET("/list", append(_listprojectconversationdefMw(), coze.ListProjectConversationDef)...)
				_project_conversation.POST("/update", append(_updateprojectconversationdefMw(), coze.UpdateProjectConversationDef)...)
			}
			{
				_upload1 := _workflow_api.Group("/upload", _upload1Mw()...)
				_upload1.POST("/auth_token", append(_getworkflowuploadauthtokenMw(), coze.GetWorkflowUploadAuthToken)...)
			}
		}
	}
	{
		_open_api := root.Group("/open_api", _open_apiMw()...)
		{
			_knowledge1 := _open_api.Group("/knowledge", _knowledge1Mw()...)
			{
				_document0 := _knowledge1.Group("/document", _document0Mw()...)
				_document0.POST("/create", append(_createdocumentopenapiMw(), coze.CreateDocumentOpenAPI)...)
				_document0.POST("/list", append(_listdocumentopenapiMw(), coze.ListDocumentOpenAPI)...)
				_document0.POST("/update", append(_updatedocumentopenapiMw(), coze.UpdateDocumentOpenAPI)...)
			}
		}
	}
	{
		_v1 := root.Group("/v1", _v1Mw()...)
		_v1.GET("/conversations", append(_listconversationsapiMw(), coze.ListConversationsApi)...)
		_conversations := _v1.Group("/conversations", _conversationsMw()...)
		_conversations.DELETE("/:conversation_id", append(_deleteconversationapiMw(), coze.DeleteConversationApi)...)
		_conversations.PUT("/:conversation_id", append(_updateconversationapiMw(), coze.UpdateConversationApi)...)
		_v1.GET("/datasets", append(_listdatasetopenapiMw(), coze.ListDatasetOpenAPI)...)
		_datasets := _v1.Group("/datasets", _datasetsMw()...)
		_datasets.DELETE("/:dataset_id", append(_deletedatasetopenapiMw(), coze.DeleteDatasetOpenAPI)...)
		_dataset_id := _datasets.Group("/:dataset_id", _dataset_idMw()...)
		_dataset_id.GET("/images", append(_listphotodocumentopenapiMw(), coze.ListPhotoDocumentOpenAPI)...)
		_dataset_id.POST("/process", append(_getdocumentprogressopenapiMw(), coze.GetDocumentProgressOpenAPI)...)
		_datasets.PUT("/:dataset_id", append(_updatedatasetopenapiMw(), coze.UpdateDatasetOpenAPI)...)
		_v1.POST("/datasets", append(_createdatasetopenapiMw(), coze.CreateDatasetOpenAPI)...)
		{
			_apps := _v1.Group("/apps", _appsMw()...)
			_apps.GET("/:app_id", append(_getonlineappdataMw(), coze.GetOnlineAppData)...)
		}
		{
			_bot0 := _v1.Group("/bot", _bot0Mw()...)
			_bot0.GET("/get_online_info", append(_getbotonlineinfoMw(), coze.GetBotOnlineInfo)...)
		}
		{
			_bots := _v1.Group("/bots", _botsMw()...)
			_bots.GET("/:bot_id", append(_opengetbotinfoMw(), coze.OpenGetBotInfo)...)
		}
		{
			_conversation0 := _v1.Group("/conversation", _conversation0Mw()...)
			_conversation0.POST("/create", append(_createconversationMw(), coze.CreateConversation)...)
			_conversation0.GET("/retrieve", append(_retrieveconversationapiMw(), coze.RetrieveConversationApi)...)
			{
				_message := _conversation0.Group("/message", _messageMw()...)
				_message.POST("/list", append(_getapimessagelistMw(), coze.GetApiMessageList)...)
			}
		}
		{
			_conversations0 := _v1.Group("/conversations", _conversations0Mw()...)
			{
				_conversation_id := _conversations0.Group("/:conversation_id", _conversation_idMw()...)
				_conversation_id.POST("/clear", append(_clearconversationapiMw(), coze.ClearConversationApi)...)
			}
		}
		{
			_files0 := _v1.Group("/files", _files0Mw()...)
			_files0.POST("/upload", append(_uploadfileopenMw(), coze.UploadFileOpen)...)
		}
		{
			_workflow := _v1.Group("/workflow", _workflowMw()...)
			_workflow.GET("/get_run_history", append(_openapigetworkflowrunhistoryMw(), coze.OpenAPIGetWorkflowRunHistory)...)
			_workflow.POST("/run", append(_openapirunflowMw(), coze.OpenAPIRunFlow)...)
			_workflow.POST("/stream_resume", append(_openapistreamresumeflowMw(), coze.OpenAPIStreamResumeFlow)...)
			_workflow.POST("/stream_run", append(_openapistreamrunflowMw(), coze.OpenAPIStreamRunFlow)...)
			{
				_conversation1 := _workflow.Group("/conversation", _conversation1Mw()...)
				_conversation1.POST("/create", append(_openapicreateconversationMw(), coze.OpenAPICreateConversation)...)
			}
		}
		{
			_workflows := _v1.Group("/workflows", _workflowsMw()...)
			_workflows.POST("/chat", append(_openapichatflowrunMw(), coze.OpenAPIChatFlowRun)...)
			_workflows.GET("/:workflow_id", append(_openapigetworkflowinfoMw(), coze.OpenAPIGetWorkflowInfo)...)
		}
	}
	{
		_v3 := root.Group("/v3", _v3Mw()...)
		_v3.POST("/chat", append(_chatv3Mw(), coze.ChatV3)...)
		_chat0 := _v3.Group("/chat", _chat0Mw()...)
		_chat0.POST("/cancel", append(_cancelchatapiMw(), coze.CancelChatApi)...)
		_chat0.GET("/retrieve", append(_retrievechatopenMw(), coze.RetrieveChatOpen)...)
		{
			_chat1 := _v3.Group("/chat", _chat1Mw()...)
			{
				_message0 := _chat1.Group("/message", _message0Mw()...)
				_message0.GET("/list", append(_listchatmessageapiMw(), coze.ListChatMessageApi)...)
			}
		}
	}
}
