/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package coze

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestAPICodegenVerifierDiscoversRealStaleGeneratedFiles(t *testing.T) {
	_, currentFile, _, ok := runtime.Caller(0)
	require.True(t, ok)
	scriptPath := filepath.Clean(filepath.Join(filepath.Dir(currentFile), "..", "..", "..", "scripts", "verify_api_codegen.sh"))
	script, err := os.ReadFile(scriptPath)
	require.NoError(t, err)
	text := string(script)

	for _, required := range []string{
		"discover_generated_files",
		"compare_generated_trees",
		"handwritten_generated_excludes",
		"SHADOW_REAL_STALE_FIXTURE=PASS",
		"stale_generated_fixture.go",
		"generated path set mismatch",
		"generated content mismatch",
	} {
		require.Contains(t, text, required)
	}

	require.Contains(t, text, "Code generated by hertz generator")
	require.Contains(t, text, "api/model")
	require.Contains(t, text, "api/router/coze")
	require.True(t, strings.Count(text, "run_clean_generation") >= 2)
}
