#!/usr/bin/env bash
#
# Copyright 2025 coze-dev Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
backend_dir="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${backend_dir}/.." && pwd)"

resolve_tool() {
  local variable_name="$1"
  local command_name="$2"
  local fallback="$3"
  local configured="${!variable_name:-}"
  if [[ -n "${configured}" && -x "${configured}" ]]; then
    printf '%s\n' "${configured}"
    return
  fi
  if command -v "${command_name}" >/dev/null 2>&1; then
    command -v "${command_name}"
    return
  fi
  if [[ -x "${fallback}" ]]; then
    printf '%s\n' "${fallback}"
    return
  fi
  printf 'missing required tool: %s\n' "${command_name}" >&2
  exit 1
}

select_sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    command -v sha256sum
    return
  fi
  if command -v shasum >/dev/null 2>&1; then
    command -v shasum
    return
  fi
  printf 'missing sha256sum or shasum\n' >&2
  exit 1
}

hz_bin="$(resolve_tool HZ_BIN hz "${HOME}/go/bin/hz")"
thriftgo_bin="$(resolve_tool THRIFTGO_BIN thriftgo "${HOME}/go/bin/thriftgo")"
sha256_bin="$(select_sha256)"
hz_version="$("${hz_bin}" --version 2>&1)"
thriftgo_version="$("${thriftgo_bin}" --version 2>&1)"
[[ "${hz_version}" == "hz version v0.9.7" ]] || {
  printf 'expected exact hz version v0.9.7, got %s\n' "${hz_version}" >&2
  exit 1
}
[[ "${thriftgo_version}" == "thriftgo 0.4.5" ]] || {
  printf 'expected exact thriftgo version 0.4.5, got %s\n' "${thriftgo_version}" >&2
  exit 1
}

handler_excludes=(
  api/handler/coze/agent_run_service.go
  api/handler/coze/app_dev_service.go
  api/handler/coze/bot_open_api_service.go
  api/handler/coze/config_service.go
  api/handler/coze/conversation_service.go
  api/handler/coze/database_service.go
  api/handler/coze/developer_api_service.go
  api/handler/coze/intelligence_service.go
  api/handler/coze/knowledge_service.go
  api/handler/coze/memory_service.go
  api/handler/coze/message_service.go
  api/handler/coze/open_apiauth_service.go
  api/handler/coze/passport_service.go
  api/handler/coze/playground_service.go
  api/handler/coze/plugin_develop_service.go
  api/handler/coze/public_product_service.go
  api/handler/coze/resource_service.go
  api/handler/coze/upload_service.go
  api/handler/coze/workbench_chat_service.go
  api/handler/coze/workbench_skill_service.go
  api/handler/coze/workbench_task_service.go
  api/handler/coze/workflow_service.go
)

handwritten_files=(
  "${handler_excludes[@]}"
  api/router/coze/admin_middleware.go
)

# These api/model files are intentionally handwritten. Every other .go file
# below api/model is generator-owned and participates in the clean manifest.
handwritten_generated_excludes=(
  api/router/register.go
  api/model/agent/langgraph/run.go
  api/model/agent/langgraph/thread.go
  api/model/workbench/diagnostic/diagnostic.go
  api/model/workbench/skill/skill_extension.go
  api/model/workbench/thread/thread.go
  api/model/workbench/tool/tool.go
  api/model/workbench/tool/official_catalog.go
  api/model/workbench/tool/mcp_management_api_contract_test.go
  api/model/workbench/tool/mcp_management_contract_test.go
)

temporary_root="$(mktemp -d)"
run_one_workspace="${temporary_root}/run-one"
run_two_workspace="${temporary_root}/run-two"
run_one_backend="${run_one_workspace}/backend"
run_two_backend="${run_two_workspace}/backend"

cleanup() {
  if [[ "${KEEP_API_CODEGEN_TMP:-0}" == "1" ]]; then
    printf 'API codegen temporary trees retained at %s\n' "${temporary_root}" >&2
    return
  fi
  rm -rf "${temporary_root}"
}
trap cleanup EXIT

hash_file() {
  local file="$1"
  if [[ "$(basename "${sha256_bin}")" == "sha256sum" ]]; then
    "${sha256_bin}" "${file}"
  else
    "${sha256_bin}" -a 256 "${file}"
  fi
}

is_handwritten_generated_exclude() {
  local candidate="$1"
  local excluded
  for excluded in "${handwritten_generated_excludes[@]}"; do
    [[ "${candidate}" == "${excluded}" ]] && return 0
  done
  return 1
}

has_official_generated_marker() {
  local file="$1"
  grep -F 'Code generated by hertz generator' "${file}" >/dev/null 2>&1
}

discover_generated_files() {
  local root="$1"
  local output="$2"
  (
    cd "${root}"
    [[ -d api/model ]] || {
      printf 'generated model tree is missing under %s\n' "${root}" >&2
      exit 1
    }
    [[ -f api/router/coze/api.go && -f api/router/coze/middleware.go ]] || {
      printf 'generated router tree is incomplete under %s\n' "${root}" >&2
      exit 1
    }

    while IFS= read -r file; do
      if ! is_handwritten_generated_exclude "${file}"; then
        printf '%s\n' "${file}"
      fi
    done < <(find api/model -type f -name '*.go' -print | LC_ALL=C sort)

    while IFS= read -r file; do
	  [[ "${file}" == *_test.go ]] && continue
      if is_handwritten_generated_exclude "${file}"; then
        continue
      fi
      case "${file}" in
        api/router/coze/api.go|api/router/coze/middleware.go)
          printf '%s\n' "${file}"
          ;;
        *)
          if has_official_generated_marker "${file}"; then
            printf '%s\n' "${file}"
          fi
          ;;
      esac
    done < <(find api/router -type f -name '*.go' -print | LC_ALL=C sort)
  ) | LC_ALL=C sort -u >"${output}"
}

# Compatibility name retained for the lightweight verifier contract test.
list_generated_files() {
  discover_generated_files "$@"
}

hash_generated_paths() {
  local root="$1"
  local paths="$2"
  local output="$3"
  (
    cd "${root}"
    while IFS= read -r file; do
      [[ -f "${file}" ]] || {
        printf 'generated output is missing: %s under %s\n' "${file}" "${root}" >&2
        exit 1
      }
      hash_file "${file}"
    done <"${paths}"
  ) >"${output}"
}

hash_generated_tree() {
  local root="$1"
  local output="$2"
  local paths="${output}.paths"
  discover_generated_files "${root}" "${paths}"
  hash_generated_paths "${root}" "${paths}" "${output}"
}

compare_generated_trees() {
  local label="$1"
  local expected_root="$2"
  local actual_root="$3"
  local work="${temporary_root}/compare-${label//[^A-Za-z0-9_.-]/_}"
  local expected_paths="${work}.expected.paths"
  local actual_paths="${work}.actual.paths"
  local expected_hashes="${work}.expected.sha256"
  local actual_hashes="${work}.actual.sha256"

  discover_generated_files "${expected_root}" "${expected_paths}"
  discover_generated_files "${actual_root}" "${actual_paths}"
  if ! cmp -s "${expected_paths}" "${actual_paths}"; then
    printf '%s generated path set mismatch\n' "${label}" >&2
    while IFS= read -r file; do
      [[ -n "${file}" ]] && printf 'missing generated path in actual: %s\n' "${file}" >&2
    done < <(comm -23 "${expected_paths}" "${actual_paths}")
    while IFS= read -r file; do
      [[ -n "${file}" ]] && printf 'unexpected generated path in actual: %s\n' "${file}" >&2
    done < <(comm -13 "${expected_paths}" "${actual_paths}")
    return 1
  fi

  hash_generated_paths "${expected_root}" "${expected_paths}" "${expected_hashes}"
  hash_generated_paths "${actual_root}" "${actual_paths}" "${actual_hashes}"
  if ! cmp -s "${expected_hashes}" "${actual_hashes}"; then
    printf '%s generated content mismatch\n' "${label}" >&2
    diff -u "${expected_hashes}" "${actual_hashes}" >&2 || true
    return 1
  fi
}

hash_named_files() {
  local root="$1"
  local output="$2"
  shift 2
  : >"${output}"
  local file
  for file in "$@"; do
    [[ -f "${root}/${file}" ]] || {
      printf 'missing protected handwritten file: %s under %s\n' "${file}" "${root}" >&2
      exit 1
    }
    (cd "${root}" && hash_file "${file}") >>"${output}"
  done
  LC_ALL=C sort -o "${output}" "${output}"
}

compare_manifests() {
  local label="$1"
  local expected="$2"
  local actual="$3"
  if cmp -s "${expected}" "${actual}"; then
    return
  fi
  printf '%s manifest mismatch\n' "${label}" >&2
  diff -u "${expected}" "${actual}" >&2 || true
  exit 1
}

copy_handwritten_handlers() {
  local target_backend="$1"
  local file
  for file in "${handwritten_files[@]}"; do
    mkdir -p "${target_backend}/$(dirname "${file}")"
    cp "${backend_dir}/${file}" "${target_backend}/${file}"
  done
}

copy_codegen_inputs() {
  local target_workspace="$1"
  local target_backend="${target_workspace}/backend"
  mkdir -p "${target_backend}"
  cp -R "${repo_root}/idl" "${target_workspace}/idl"
  cp "${backend_dir}/.hz" "${target_backend}/.hz"
  cp "${backend_dir}/go.mod" "${target_backend}/go.mod"
  copy_handwritten_handlers "${target_backend}"
}

postprocess_generated_middleware() {
  local target_backend="$1"
  local middleware_file="${target_backend}/api/router/coze/middleware.go"
  local temporary_file="${middleware_file}.postprocess"
  if ! awk '
    BEGIN { replaced = 0; failed = 0 }
    $0 == "func _adminMw() []app.HandlerFunc {" {
      opening = $0
      if ((getline comment) <= 0 || (getline body) <= 0 || (getline closing) <= 0 ||
          comment != "\t// your code..." || body != "\treturn nil" || closing != "}") {
        failed = 1
        exit
      }
      print opening
      print "\treturn []app.HandlerFunc{adminAuthMiddlewareFactory()}"
      print "}"
      replaced++
      next
    }
    { print }
    END { if (failed || replaced != 1) exit 42 }
  ' "${middleware_file}" >"${temporary_file}"; then
    rm -f "${temporary_file}"
    printf 'GENERATED_MIDDLEWARE_POSTPROCESS failed for %s\n' "${middleware_file}" >&2
    exit 1
  fi
  mv "${temporary_file}" "${middleware_file}"
}

postprocess_generated_license_headers() {
  local target_backend="$1"
  local generated_paths="${temporary_root}/generated-license-paths.$RANDOM"
  local file
  local target_file
  local temporary_file

  discover_generated_files "${target_backend}" "${generated_paths}"
  while IFS= read -r file; do
    target_file="${target_backend}/${file}"
    if head -n 5 "${target_file}" | grep -q 'Copyright.*coze-dev Authors'; then
      continue
    fi
    temporary_file="${target_file}.license"
    cat >"${temporary_file}" <<'HEADER'
/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

HEADER
    cat "${target_file}" >>"${temporary_file}"
    mv "${temporary_file}" "${target_file}"
  done <"${generated_paths}"
}

run_clean_generation() {
  local target_workspace="$1"
  local target_backend="${target_workspace}/backend"
  local -a exclude_args=()
  local file

  copy_codegen_inputs "${target_workspace}"
  for file in "${handler_excludes[@]}"; do
    exclude_args+=(--exclude_file "${file}")
  done
  (
    cd "${target_backend}"
    PATH="$(dirname "${hz_bin}"):$(dirname "${thriftgo_bin}"):${PATH}" \
      "${hz_bin}" update -idl ../idl/api.thrift -enable_extends "${exclude_args[@]}"
  )
  postprocess_generated_middleware "${target_backend}"
  postprocess_generated_license_headers "${target_backend}"
}

copy_discovered_generated_tree() {
  local source_root="$1"
  local target_root="$2"
  local paths="${temporary_root}/shadow-real.paths"
  discover_generated_files "${source_root}" "${paths}"
  local file
  while IFS= read -r file; do
    mkdir -p "${target_root}/$(dirname "${file}")"
    cp "${source_root}/${file}" "${target_root}/${file}"
  done <"${paths}"
}

hash_generated_tree "${backend_dir}" "${temporary_root}/real-generated.before"
hash_named_files "${backend_dir}" "${temporary_root}/real-handwritten.before"   "${handwritten_files[@]}" "${handwritten_generated_excludes[@]}"

run_clean_generation "${run_one_workspace}"
run_clean_generation "${run_two_workspace}"

hash_named_files "${run_one_backend}" "${temporary_root}/run-one-handlers.after" "${handwritten_files[@]}"
hash_named_files "${run_two_backend}" "${temporary_root}/run-two-handlers.after" "${handwritten_files[@]}"
hash_named_files "${backend_dir}" "${temporary_root}/real-handlers-only" "${handwritten_files[@]}"
compare_manifests "HANDWRITTEN_RUN1_UNCHANGED" "${temporary_root}/real-handlers-only" "${temporary_root}/run-one-handlers.after"
compare_manifests "HANDWRITTEN_RUN2_UNCHANGED" "${temporary_root}/real-handlers-only" "${temporary_root}/run-two-handlers.after"

compare_generated_trees "CLEAN_RUN1_VS_CLEAN_RUN2" "${run_one_backend}" "${run_two_backend}"
compare_generated_trees "REAL_VS_CLEAN_RUN1" "${run_one_backend}" "${backend_dir}"

for generated_router in "${run_one_backend}/api/router/coze/api.go" "${run_two_backend}/api/router/coze/api.go"; do
  if grep -F '/build/artifact' "${generated_router}" >/dev/null; then
    printf 'LEGACY_ARTIFACT_ROUTE_ABSENT failed for %s\n' "${generated_router}" >&2
    exit 1
  fi
done

shadow_real_backend="${temporary_root}/shadow-real/backend"
copy_discovered_generated_tree "${backend_dir}" "${shadow_real_backend}"
stale_fixture_path="${shadow_real_backend}/api/model/appdev/stale_generated_fixture.go"
mkdir -p "$(dirname "${stale_fixture_path}")"
cat >"${stale_fixture_path}" <<'STALE'
package appdev

// Code generated by hertz generator. DO NOT EDIT.
type staleGeneratedFixture struct{}
STALE
stale_diagnostic="${temporary_root}/shadow-real-stale.diagnostic"
if compare_generated_trees "SHADOW_REAL_STALE" "${run_one_backend}" "${shadow_real_backend}" >"${stale_diagnostic}" 2>&1; then
  printf 'SHADOW_REAL_STALE_FIXTURE unexpectedly matched the clean tree\n' >&2
  exit 1
fi
if ! grep -F 'unexpected generated path in actual: api/model/appdev/stale_generated_fixture.go' "${stale_diagnostic}" >/dev/null; then
  printf 'SHADOW_REAL_STALE_FIXTURE did not report the stale path\n' >&2
  cat "${stale_diagnostic}" >&2
  exit 1
fi

hash_generated_tree "${backend_dir}" "${temporary_root}/real-generated.after"
hash_named_files "${backend_dir}" "${temporary_root}/real-handwritten.after"   "${handwritten_files[@]}" "${handwritten_generated_excludes[@]}"
compare_manifests "REAL_WORKSPACE_GENERATED_BEFORE_VS_AFTER"   "${temporary_root}/real-generated.before" "${temporary_root}/real-generated.after"
compare_manifests "REAL_WORKSPACE_HANDWRITTEN_BEFORE_VS_AFTER"   "${temporary_root}/real-handwritten.before" "${temporary_root}/real-handwritten.after"

printf 'WORKSPACE_READ_ONLY_SHA256=PASS\n'
printf 'GENERATED_BASELINE_SHA256=PASS\n'
printf 'HANDLERS_EXCLUDED_SHA256=PASS\n'
printf 'CODEGEN_DETERMINISTIC_SHA256=PASS\n'
printf 'STALE_GENERATED_FIXTURE=PASS\n'
printf 'SHADOW_REAL_STALE_FIXTURE=PASS\n'
printf 'FILES_HASHED=%s\n' "$(wc -l <"${temporary_root}/real-generated.after" | tr -d ' ')"
