// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

package sandbox

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"sync"
	"time"

	domainsandbox "github.com/coze-dev/coze-studio/backend/domain/sandbox"
	infrasandbox "github.com/coze-dev/coze-studio/backend/infra/sandbox"
)

const (
	MinCapacityLeaseDuration = time.Second
	MaxCapacityLeaseDuration = time.Hour
	maxOpaqueLeaseTokenBytes = 256
	capacityLeaseTokenBytes  = 16
	capacityCleanupTimeout   = time.Second
)

// DrainFence is opaque, CSPRNG-generated lifecycle ownership. It is never
// accepted from an external API or projected into responses or audits.
type DrainFence = string

// DrainHandle is an internal lifecycle capability. Current is the only token
// that can authorize a transition; Previous is historical and never authorizes
// rolling the lifecycle epoch backward. Neither fence is externally projected.
type DrainHandle = infrasandbox.DrainHandle

// ActivationCompensationResult reports whether an activation owner restored
// its own drain gate, had already restored it, or was superseded by a newer
// lifecycle operation. It remains internal to the control plane.
type ActivationCompensationResult = infrasandbox.ActivationCompensationResult

const (
	ActivationCompensationStale          = infrasandbox.ActivationCompensationStale
	ActivationCompensationApplied        = infrasandbox.ActivationCompensationApplied
	ActivationCompensationAlreadyApplied = infrasandbox.ActivationCompensationAlreadyApplied
)

// CapacityLimiter is deliberately transport-neutral. The opaque token is only
// generated by an internal application request, then reused for every retry of
// that logical request. It must never be accepted from an external API or
// projected to API or audit data.
type CapacityLimiter interface {
	Acquire(
		ctx context.Context,
		providerKey string,
		token string,
		fence string,
		capacity int,
		duration time.Duration,
	) (expiryUnixMilli int64, err error)
	Renew(
		ctx context.Context,
		providerKey string,
		token string,
		fence string,
		renewalID string,
		duration time.Duration,
	) (expiryUnixMilli int64, err error)
	Release(ctx context.Context, providerKey, token, fence string) error
}

type capacityLease struct {
	mu               sync.Mutex
	limiter          CapacityLimiter
	providerKey      string
	token            string
	fence            string
	duration         time.Duration
	expiryUnixMilli  int64
	pendingRenewalID string
	released         bool
}

func (*capacityLease) String() string   { return "capacityLease{secrets:<redacted>}" }
func (*capacityLease) GoString() string { return "capacityLease{secrets:<redacted>}" }

func (*capacityLease) Format(state fmt.State, _ rune) {
	_, _ = io.WriteString(state, "capacityLease{secrets:<redacted>}")
}

func newCapacityLease(
	limiter CapacityLimiter,
	providerKey string,
	token string,
	fence string,
	duration time.Duration,
	expiryUnixMilli int64,
) (*capacityLease, error) {
	if limiter == nil || domainsandbox.ValidateProviderKey(providerKey) != nil ||
		!validOpaqueLeaseToken(token) || !validOpaqueLeaseToken(fence) ||
		len(token) > maxOpaqueLeaseTokenBytes || len(fence) > maxOpaqueLeaseTokenBytes ||
		!validCapacityLeaseDuration(duration) || expiryUnixMilli <= 0 {
		return nil, domainsandbox.ErrUnavailable
	}
	return &capacityLease{
		limiter:         limiter,
		providerKey:     providerKey,
		token:           token,
		fence:           fence,
		duration:        duration,
		expiryUnixMilli: expiryUnixMilli,
	}, nil
}

func (l *capacityLease) renew(ctx context.Context) error {
	return l.renewWithIdentity(ctx, "")
}

func (l *capacityLease) renewWithID(ctx context.Context, renewalID string) error {
	if !validOpaqueLeaseToken(renewalID) {
		return domainsandbox.ErrInvalidInput
	}
	return l.renewWithIdentity(ctx, renewalID)
}

func (l *capacityLease) renewWithIdentity(ctx context.Context, stableRenewalID string) error {
	if l == nil || ctx == nil {
		return domainsandbox.ErrInvalidInput
	}
	if err := ctx.Err(); err != nil {
		return err
	}

	l.mu.Lock()
	defer l.mu.Unlock()
	if l.released {
		return domainsandbox.ErrExecutionForbidden
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if l.pendingRenewalID == "" {
		if stableRenewalID != "" {
			l.pendingRenewalID = stableRenewalID
		} else {
			renewalID, err := newOpaqueLeaseToken()
			if err != nil {
				return err
			}
			l.pendingRenewalID = renewalID
		}
	} else if stableRenewalID != "" && l.pendingRenewalID != stableRenewalID {
		return domainsandbox.ErrExecutionForbidden
	}
	expiryUnixMilli, err := l.limiter.Renew(
		ctx,
		l.providerKey,
		l.token,
		l.fence,
		l.pendingRenewalID,
		l.duration,
	)
	if err := normalizeOperationalError(ctx, err); err != nil {
		return err
	}
	if expiryUnixMilli <= 0 {
		return domainsandbox.ErrUnavailable
	}
	l.expiryUnixMilli = expiryUnixMilli
	l.pendingRenewalID = ""
	return nil
}

func deriveOpaqueLeaseToken(namespace string, values ...string) string {
	hash := sha256.New()
	_, _ = io.WriteString(hash, namespace)
	for _, value := range values {
		_, _ = hash.Write([]byte{0})
		_, _ = io.WriteString(hash, value)
	}
	sum := hash.Sum(nil)
	return base64.RawURLEncoding.EncodeToString(sum[:capacityLeaseTokenBytes])
}

func (l *capacityLease) snapshot() (providerKey, token, fence string, expiryUnixMilli int64, err error) {
	if l == nil {
		return "", "", "", 0, domainsandbox.ErrInvalidInput
	}
	l.mu.Lock()
	defer l.mu.Unlock()
	if l.released || l.expiryUnixMilli <= 0 {
		return "", "", "", 0, domainsandbox.ErrExecutionForbidden
	}
	return l.providerKey, l.token, l.fence, l.expiryUnixMilli, nil
}

func (l *capacityLease) release(ctx context.Context) error {
	if l == nil || ctx == nil {
		return domainsandbox.ErrInvalidInput
	}

	l.mu.Lock()
	defer l.mu.Unlock()
	if l.released {
		return nil
	}
	cleanupContext, cancel := newCapacityCleanupContext(ctx)
	defer cancel()
	if err := normalizeOperationalError(
		cleanupContext,
		l.limiter.Release(cleanupContext, l.providerKey, l.token, l.fence),
	); err != nil {
		return err
	}
	l.released = true
	return nil
}

func validCapacityLeaseDuration(duration time.Duration) bool {
	return duration >= MinCapacityLeaseDuration &&
		duration <= MaxCapacityLeaseDuration &&
		duration%time.Millisecond == 0
}

func newCapacityCleanupContext(parent context.Context) (context.Context, context.CancelFunc) {
	return context.WithTimeout(context.WithoutCancel(parent), capacityCleanupTimeout)
}

func newOpaqueLeaseToken() (string, error) {
	return generateOpaqueLeaseToken(rand.Reader)
}

func generateOpaqueLeaseToken(entropy io.Reader) (string, error) {
	if entropy == nil {
		return "", domainsandbox.ErrConfigurationInvalid
	}
	raw := make([]byte, capacityLeaseTokenBytes)
	if _, err := io.ReadFull(entropy, raw); err != nil {
		return "", domainsandbox.ErrUnavailable
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

func validOpaqueLeaseToken(token string) bool {
	if len(token) != base64.RawURLEncoding.EncodedLen(capacityLeaseTokenBytes) {
		return false
	}
	decoded, err := base64.RawURLEncoding.DecodeString(token)
	return err == nil && len(decoded) == capacityLeaseTokenBytes
}

func normalizeOperationalError(ctx context.Context, err error) error {
	if err == nil {
		return nil
	}
	if ctx != nil && ctx.Err() != nil {
		return ctx.Err()
	}
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
		return err
	}
	if domainsandbox.ErrorCodeOf(err) != "" {
		return err
	}
	return domainsandbox.ErrUnavailable
}
