/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package coze

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/cloudwego/eino/schema"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/coze-dev/coze-studio/backend/api/model/admin/config"
	bizConf "github.com/coze-dev/coze-studio/backend/bizpkg/config"
	baseconfig "github.com/coze-dev/coze-studio/backend/bizpkg/config/base"
	"github.com/coze-dev/coze-studio/backend/bizpkg/config/modelmgr"
	"github.com/coze-dev/coze-studio/backend/bizpkg/llm/modelbuilder"
	"github.com/coze-dev/coze-studio/backend/infra/embedding/impl"
	"github.com/coze-dev/coze-studio/backend/pkg/kvstore"
	"github.com/coze-dev/coze-studio/backend/pkg/lang/conv"
	"github.com/coze-dev/coze-studio/backend/pkg/lang/ptr"
	"github.com/coze-dev/coze-studio/backend/pkg/logs"
)

type basicConfigurationBackend interface {
	GetBaseConfigWithRevision(context.Context) (*config.BasicConfiguration, string, error)
	SaveBaseConfig(context.Context, baseconfig.BasicConfigurationPatch, string) (string, error)
}

type saveBasicConfigurationRequest struct {
	Configuration    *basicConfigurationPatchPayload `json:"configuration"`
	ExpectedRevision *string                         `json:"expected_revision"`
}

type basicConfigurationPatchPayload struct {
	AdminEmails             *string                     `json:"admin_emails"`
	DisableUserRegistration *bool                       `json:"disable_user_registration"`
	AllowRegistrationEmail  *string                     `json:"allow_registration_email"`
	PluginConfiguration     *config.PluginConfiguration `json:"plugin_configuration"`
	ServerHost              *string                     `json:"server_host"`
	CodeRunnerType          json.RawMessage             `json:"code_runner_type"`
	SandboxConfig           json.RawMessage             `json:"sandbox_config"`
}

// GetBasicConfiguration .
// @router /api/admin/config/basic/get [GET]
func GetBasicConfiguration(ctx context.Context, c *app.RequestContext) {
	getBasicConfiguration(ctx, c, bizConf.Base())
}

func getBasicConfiguration(ctx context.Context, c *app.RequestContext, backend basicConfigurationBackend) {
	baseConfig, revision, err := backend.GetBaseConfigWithRevision(ctx)
	if err != nil {
		basicConfigurationError(ctx, c, err)
		return
	}
	c.JSON(consts.StatusOK, map[string]any{
		"configuration": baseConfig,
		"revision":      revision,
	})
}

// SaveBasicConfiguration .
// @router /api/admin/config/basic/save [POST]
func SaveBasicConfiguration(ctx context.Context, c *app.RequestContext) {
	saveBasicConfiguration(ctx, c, bizConf.Base())
}

func saveBasicConfiguration(ctx context.Context, c *app.RequestContext, backend basicConfigurationBackend) {
	var req saveBasicConfigurationRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if req.Configuration == nil || req.ExpectedRevision == nil || strings.TrimSpace(*req.ExpectedRevision) == "" {
		invalidParamRequestResponse(c, "configuration and expected_revision are required")
		return
	}
	patch := req.Configuration.toPatch()
	if patch.IsEmpty() {
		invalidParamRequestResponse(c, "configuration patch is empty")
		return
	}
	if patch.ServerHost != nil {
		if err = validateBasicConfigurationServerHost(*patch.ServerHost); err != nil {
			invalidParamRequestResponse(c, err.Error())
			return
		}
	}

	revision, err := backend.SaveBaseConfig(ctx, patch, strings.TrimSpace(*req.ExpectedRevision))
	if err != nil {
		basicConfigurationError(ctx, c, err)
		return
	}
	c.JSON(consts.StatusOK, map[string]any{"revision": revision})
}

func (p *basicConfigurationPatchPayload) toPatch() baseconfig.BasicConfigurationPatch {
	patch := baseconfig.BasicConfigurationPatch{
		DisableUserRegistration: p.DisableUserRegistration,
		PluginConfiguration:     p.PluginConfiguration,
	}
	if p.AdminEmails != nil {
		value := strings.TrimSpace(*p.AdminEmails)
		patch.AdminEmails = &value
	}
	if p.AllowRegistrationEmail != nil {
		value := strings.TrimSpace(*p.AllowRegistrationEmail)
		patch.AllowRegistrationEmail = &value
	}
	if p.ServerHost != nil {
		value := strings.TrimSpace(*p.ServerHost)
		patch.ServerHost = &value
	}
	return patch
}

func validateBasicConfigurationServerHost(host string) error {
	if host == "" {
		return errors.New("ServerHost is empty")
	}
	if strings.Contains(host, "://") {
		u, parseErr := url.Parse(host)
		if parseErr != nil || u.Host == "" || (u.Scheme != "http" && u.Scheme != "https") {
			return errors.New("ServerHost is invalid URL, require http/https")
		}
	} else {
		h, p, splitErr := net.SplitHostPort(host)
		if splitErr != nil || h == "" {
			return errors.New("ServerHost must be hostname:port or http(s) URL")
		}
		port, portErr := strconv.Atoi(p)
		if portErr != nil || port <= 0 || port > 65535 {
			return errors.New("ServerHost port is invalid")
		}
	}
	return nil
}

func basicConfigurationError(ctx context.Context, c *app.RequestContext, err error) {
	status, code, message := basicConfigurationErrorContract(err)
	if status == http.StatusInternalServerError {
		logs.CtxErrorf(ctx, "[BasicConfiguration] request failed: %v", err)
	}
	c.AbortWithStatusJSON(status, map[string]any{
		"code":       status,
		"error_code": code,
		"msg":        message,
	})
}

func basicConfigurationErrorContract(err error) (int, string, string) {
	if errors.Is(err, kvstore.ErrVersionConflict) {
		return http.StatusConflict, "BASE_CONFIG_VERSION_CONFLICT", "base configuration revision is stale"
	}
	return http.StatusInternalServerError, "BASE_CONFIG_INTERNAL", "basic configuration request failed"
}

// GetKnowledgeConfig .
// @router /api/admin/config/knowledge/get [GET]
func GetKnowledgeConfig(ctx context.Context, c *app.RequestContext) {
	knowledgeConfig, err := bizConf.Knowledge().GetKnowledgeConfig(ctx)
	if err != nil {
		internalServerErrorResponse(ctx, c, fmt.Errorf("get knowledge config failed: %w", err))
		return
	}

	resp := new(config.GetKnowledgeConfigResp)
	resp.KnowledgeConfig = knowledgeConfig

	c.JSON(consts.StatusOK, resp)
}

// UpdateKnowledgeConfig .
// @router /api/admin/config/knowledge/save [POST]
func UpdateKnowledgeConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.UpdateKnowledgeConfigReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.KnowledgeConfig == nil {
		invalidParamRequestResponse(c, "KnowledgeConfig is nil")
		return
	}

	if req.KnowledgeConfig.EmbeddingConfig == nil {
		invalidParamRequestResponse(c, "EmbeddingConfig is nil")
		return
	}

	if req.KnowledgeConfig.EmbeddingConfig.Connection == nil {
		invalidParamRequestResponse(c, "Connection is nil")
		return
	}

	if req.KnowledgeConfig.EmbeddingConfig.Connection.EmbeddingInfo == nil {
		invalidParamRequestResponse(c, "EmbeddingInfo is nil")
		return
	}

	embedding, err := impl.GetEmbedding(ctx, req.KnowledgeConfig.EmbeddingConfig)
	if err != nil {
		invalidParamRequestResponse(c, fmt.Sprintf("get embedding failed: %v", err))
		return
	}

	if req.KnowledgeConfig.EmbeddingConfig.Connection.EmbeddingInfo.Dims <= 0 {
		req.KnowledgeConfig.EmbeddingConfig.Connection.EmbeddingInfo.Dims = int32(embedding.Dimensions())

		embedding, err = impl.GetEmbedding(ctx, req.KnowledgeConfig.EmbeddingConfig)
		if err != nil {
			invalidParamRequestResponse(c, fmt.Sprintf("get embedding failed: %v", err))
			return
		}
	}

	denseEmbeddings, err := embedding.EmbedStrings(ctx, []string{"test"})
	if err != nil {
		invalidParamRequestResponse(c, fmt.Sprintf("embed test string failed: %v", err))
		return
	}

	if len(denseEmbeddings) == 0 {
		invalidParamRequestResponse(c, fmt.Sprintf("embed test string failed: %v", err))
		return
	}

	logs.CtxDebugf(ctx, "embed test string result: %d, expect %d",
		len(denseEmbeddings[0]), req.KnowledgeConfig.EmbeddingConfig.Connection.EmbeddingInfo.Dims)
	if len(denseEmbeddings[0]) != int(req.KnowledgeConfig.EmbeddingConfig.Connection.EmbeddingInfo.Dims) {
		invalidParamRequestResponse(c, fmt.Sprintf("embed test string failed: dims not match, expect %d, got %d",
			req.KnowledgeConfig.EmbeddingConfig.Connection.EmbeddingInfo.Dims, len(denseEmbeddings[0])))
		return
	}

	err = bizConf.Knowledge().SaveKnowledgeConfig(ctx, req.KnowledgeConfig)
	if err != nil {
		internalServerErrorResponse(ctx, c, fmt.Errorf("save knowledge config failed: %w", err))
		return
	}

	resp := new(config.UpdateKnowledgeConfigResp)

	c.JSON(consts.StatusOK, resp)
}

// GetModelList .
// @router /api/admin/config/model/list [GET]
func GetModelList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.GetModelListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	modelList, err := bizConf.ModelConf().GetProviderModelList(ctx)
	if err != nil {
		internalServerErrorResponse(ctx, c, fmt.Errorf("get model list failed: %w", err))
		return
	}

	resp := new(config.GetModelListResp)
	resp.ProviderModelList = modelList

	c.JSON(consts.StatusOK, resp)
}

// CreateModel .
// @router /api/admin/config/model/create [POST]
func CreateModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.CreateModelReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	modelBuilder, err := modelbuilder.NewModelBuilder(req.ModelClass, &config.Model{
		EnableBase64URL: req.EnableBase64URL,
		Connection:      req.Connection,
	})
	if err != nil {
		invalidParamRequestResponse(c, fmt.Sprintf("create model builder failed: %v", err))
		return
	}

	logs.CtxDebugf(ctx, "create model req: %s, conn: %s", conv.DebugJsonToStr(req), conv.DebugJsonToStr(req.Connection.BaseConnInfo))

	chatModel, err := modelBuilder.Build(ctx, &modelbuilder.LLMParams{EnableThinking: ptr.Of(false)})
	if err != nil {
		invalidParamRequestResponse(c, fmt.Sprintf("build model failed: %v", err))
		return
	}

	respMsgs, err := chatModel.Generate(ctx, []*schema.Message{
		schema.SystemMessage("Just answer with a number, no explanation."),
		schema.UserMessage("1+1=?"),
	})
	if err != nil {
		invalidParamRequestResponse(c, fmt.Sprintf("generate model failed: %v", err))
		return
	}

	logs.CtxDebugf(ctx, "chatModel.Generate resp : %s", conv.DebugJsonToStr(respMsgs))

	id, err := bizConf.ModelConf().CreateModel(ctx, req.ModelClass, req.ModelName, req.Connection, &modelmgr.ModelExtra{
		EnableBase64URL: req.EnableBase64URL,
	})
	if err != nil {
		invalidParamRequestResponse(c, fmt.Sprintf("create model failed: %v", err))
		return
	}

	resp := new(config.CreateModelResp)
	resp.ID = id

	c.JSON(consts.StatusOK, resp)
}

// DeleteModel .
// @router /api/admin/config/model/delete [POST]
func DeleteModel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.DeleteModelReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err = bizConf.ModelConf().DeleteModel(ctx, req.ID)
	if err != nil {
		internalServerErrorResponse(ctx, c, fmt.Errorf("delete model failed: %w", err))
		return
	}

	resp := new(config.DeleteModelResp)

	c.JSON(consts.StatusOK, resp)
}
